# This file adds best practice fleets to all new Fleet Premium instances: https://fleetdm.com/guides/fleets#best-practice

apiVersion: v1
kind: team
spec:
  fleet:
    name: 💻 Workstations
---
apiVersion: v1
kind: team
spec:
  fleet:
    name: ☁️ IT servers
---
apiVersion: v1
kind: team
spec:
  fleet:
    name: 📱🔐 Personal mobile devices
---
apiVersion: v1
kind: team
spec:
  fleet:
    name: 📱🏢 Employee-issued mobile devices
---
apiVersion: v1
kind: team
spec:
  fleet:
    name: 🖥️ Dedicated devices
