terraform {
  required_providers {
    random = { source = "hashicorp/random", version = "~> 3.6" }
  }
}

#####################################
# Inputs
#####################################
variable "endpoint" {
  description = "DB endpoint in host:port form (e.g. cluster-xyz.us-east-1.rds.amazonaws.com:3306)"
  type        = string
}

variable "admin_username" {
  description = "MySQL admin username to run CREATE USER / GRANT"
  type        = string
}

variable "admin_password" {
  description = "MySQL admin password"
  type        = string
  sensitive   = true
}

variable "developers" {
  description = "List of developer MySQL usernames to create/grant"
  type        = list(string)
}

variable "database_name" {
  description = "Database to grant privileges on"
  type        = string
  default     = "fleet"
}

#####################################
# Fixed VPN subnets (as host wildcards)
#####################################
locals {
  vpn_host_patterns = [
    "10.255.1.%",
    "10.255.2.%",
    "10.255.3.%"
  ]

  # Split host:port
  endpoint_host = split(":", var.endpoint)[0]
  endpoint_port = tonumber(try(split(":", var.endpoint)[1], "3306"))
}

#####################################
# One random password per developer
#####################################
resource "random_password" "dev_pw" {
  for_each = toset(var.developers)

  length           = 24
  special          = true
  override_special = "!@#$%^&*()-_=+[]{}<>?"
}

# Escape passwords for safe SQL single-quoted strings:
# - escape backslashes first, then single quotes
locals {
  dev_pw_escaped = {
    for u, rp in random_password.dev_pw :
    u => replace(
      replace(rp.result, "\\", "\\\\"),
      "'", "\\'"
    )
  }
}

#####################################
# Render SQL (idempotent)
#####################################
# Strategy:
# - Create per-host accounts explicitly (no reliance on implicit GRANT account creation)
# - Ensure password is set (ALTER USER after CREATE IF NOT EXISTS)
# - Grant ALL on <db>.*
# - One FLUSH PRIVILEGES at end
locals {
  sql = <<-SQL
    -- Generated by Terraform module mysql_dev_access
    SET SESSION sql_log_bin = 0;

    %{~for dev in var.developers~}
      %{~for host in local.vpn_host_patterns~}
    CREATE USER IF NOT EXISTS '${dev}'@'${host}' IDENTIFIED BY '${local.dev_pw_escaped[dev]}';
    ALTER USER '${dev}'@'${host}' IDENTIFIED BY '${local.dev_pw_escaped[dev]}';
    GRANT rds_superuser_role TO '${dev}'@'${host}';
    GRANT ALL PRIVILEGES ON `${var.database_name}`.* TO '${dev}'@'${host}';
      %{~endfor~}
    %{~endfor~}

    FLUSH PRIVILEGES;
  SQL
}

#####################################
# Apply SQL via mysql client
#####################################
# Re-runs when any trigger value changes.
resource "null_resource" "apply_sql" {
  triggers = {
    endpoint       = var.endpoint
    admin_username = var.admin_username
    # Password intentionally NOT a trigger (avoid churn on no-op applies)
    db              = var.database_name
    developers_hash = md5(join(",", sort(var.developers)))
    pw_hash         = md5(join(",", [for u in sort(var.developers) : random_password.dev_pw[u].result]))
    sql_hash        = md5(local.sql)
  }

  provisioner "local-exec" {
    # Requires `mysql` client available in PATH on the runner
    command = <<-EOT
      mysql --protocol=TCP \
            --host='${local.endpoint_host}' \
            --port='${local.endpoint_port}' \
            --user='${var.admin_username}' \
            --password='${var.admin_password}' \
            --execute="$(cat <<'SQL'
${local.sql}
SQL
)"
    EOT
  }
}

#####################################
# Outputs
#####################################
output "developer_passwords" {
  description = "Map of developer -> generated password"
  value       = { for u in var.developers : u => random_password.dev_pw[u].result }
  sensitive   = true
}

