package tables

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"path"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func TestUp_20260827170502(t *testing.T) {
	db := applyUpToPrev(t)

	const (
		publishedInstall   = "#!/bin/sh\ninstaller -pkg app.pkg\n"
		publishedUninstall = "#!/bin/sh\nrm -rf /Applications/App.app\n"
		adminInstall       = "#!/bin/sh\necho custom install\n"
		adminUninstall     = "#!/bin/sh\necho custom uninstall\n"
		// An install script Fleet published for an earlier version, still in the hash
		// map because the generator walks all of history.
		outdatedInstall = "#!/bin/sh\ninstaller -pkg app-0.9.pkg\n"
		// Most Fleet scripts carry multi-byte characters, and this is the only place
		// MySQL's SHA2 over the utf8mb4 column is checked against Go's sha256 of the
		// same bytes, so one app publishes a script that has them.
		unicodeInstall = "#!/bin/sh\n# café — naïve ✓ 你好\ninstaller -pkg app.pkg\n"
		// Rows are pinned to beforeCutoff so they fall inside the window the corpus
		// can speak to, since a freshly inserted row would otherwise be stamped now.
		corpusCutoff = "2026-08-01T00:00:00Z"
		beforeCutoff = "2026-07-01 00:00:00"
		afterCutoff  = "2026-08-15 12:00:00"
	)

	// The migration downloads the hashes published by tools/software/fma-script-hashes.
	// Serve a small set so the test states its own expectations instead of depending
	// on which scripts Fleet happened to publish.
	header := fmt.Sprintf("# Generated by tools/software/fma-script-hashes. DO NOT EDIT.\n# to bbbbbbbb %s\n", corpusCutoff)
	serveScriptHashMaps(t,
		header+fmt.Sprintf("%s foo/darwin\n%s foo/darwin\n%s foo/darwin\n%s bar/darwin\n", sha256Hex(publishedInstall), sha256Hex(outdatedInstall), sha256Hex(unicodeInstall), sha256Hex(publishedInstall)),
		header+fmt.Sprintf("%s foo/darwin\n%s bar/darwin\n%s baz/windows\n", sha256Hex(publishedUninstall), sha256Hex(publishedUninstall), substitutedScriptMarker),
	)

	// script_contents is deduplicated by content, so the same script shared by two
	// installers resolves to the row that already holds it.
	scriptID := func(contents string) int64 {
		return execNoErrLastID(t, db, `
			INSERT INTO script_contents (contents, md5_checksum) VALUES (?, UNHEX(MD5(?)))
			ON DUPLICATE KEY UPDATE id = LAST_INSERT_ID(id)`, contents, contents)
	}
	maintainedAppID := func(slug string) int64 {
		return execNoErrLastID(t, db, `INSERT INTO fleet_maintained_apps (name, slug, platform, unique_identifier) VALUES (?, ?, 'darwin', ?)`, slug, slug, slug)
	}
	insertInstaller := func(name string, teamID int64, fmaID any, filename string, install string, uninstall string) int64 {
		titleID := execNoErrLastID(t, db, `INSERT INTO software_titles (name, source) VALUES (?, 'apps')`, name)
		return execNoErrLastID(t, db, `
			INSERT INTO software_installers
				(team_id, global_or_team_id, title_id, filename, extension, version, platform,
				 install_script_content_id, uninstall_script_content_id, storage_id,
				 package_ids, patch_query, fleet_maintained_app_id)
			VALUES (NULL, ?, ?, ?, 'pkg', '1.0', 'darwin', ?, ?, ?, '', '', ?)`,
			teamID, titleID, filename, scriptID(install), scriptID(uninstall), filename, fmaID)
	}

	foo := maintainedAppID("foo/darwin")
	bar := maintainedAppID("bar/darwin")
	baz := maintainedAppID("baz/windows")

	// No team (global_or_team_id 0), everything as Fleet published it.
	untouched := insertInstaller("Untouched", 0, foo, "app.pkg", publishedInstall, publishedUninstall)
	// Only the install script was replaced.
	installEdited := insertInstaller("Install edited", 0, foo, "app.pkg", adminInstall, publishedUninstall)
	// Both scripts replaced, on a team rather than no-team.
	bothEdited := insertInstaller("Both edited", 1, foo, "app.pkg", adminInstall, adminUninstall)
	// Still on the script Fleet published for an older version, which is what the
	// cron left behind when it skipped script-only updates. Not an admin edit.
	outdatedScript := insertInstaller("Outdated script", 0, foo, "app-0.9.pkg", outdatedInstall, publishedUninstall)
	// Matches only if MySQL and the generator agree on multi-byte characters.
	unicodeScript := insertInstaller("Unicode script", 0, foo, "app.pkg", unicodeInstall, publishedUninstall)
	// A published script, but belonging to a different app than the one it was published for.
	wrongApp := insertInstaller("Wrong app", 0, bar, "app.pkg", unicodeInstall, publishedUninstall)
	// Changed after the corpus was cut, so the corpus can't speak to it.
	changedAfterCutoff := insertInstaller("Changed after cutoff", 0, foo, "app.pkg", adminInstall, adminUninstall)
	// This app's uninstall script gets substituted with installer metadata, so the flag
	// has to stay off even for a script no hash recognizes.
	substitutedUninstall := insertInstaller("Substituted uninstall", 0, baz, "app.exe", adminInstall, adminUninstall)
	// Not a Fleet-maintained app at all.
	notMaintained := insertInstaller("Not maintained", 0, nil, "custom.pkg", adminInstall, adminUninstall)

	execNoErr(t, db, `UPDATE software_installers SET updated_at = ?`, beforeCutoff)
	execNoErr(t, db, `UPDATE software_installers SET updated_at = ? WHERE id = ?`, afterCutoff, changedAfterCutoff)

	// Apply current migration.
	applyNext(t, db)

	flags := func(id int64) (install bool, uninstall bool) {
		var row struct {
			Install   bool `db:"install_script_edited"`
			Uninstall bool `db:"uninstall_script_edited"`
		}
		require.NoError(t, db.Get(&row, `SELECT install_script_edited, uninstall_script_edited FROM software_installers WHERE id = ?`, id))
		return row.Install, row.Uninstall
	}

	install, uninstall := flags(untouched)
	require.False(t, install)
	require.False(t, uninstall)

	install, uninstall = flags(installEdited)
	require.True(t, install)
	require.False(t, uninstall)

	install, uninstall = flags(bothEdited)
	require.True(t, install)
	require.True(t, uninstall)

	install, uninstall = flags(outdatedScript)
	require.False(t, install, "a script Fleet published for an earlier version is not an admin edit")
	require.False(t, uninstall)

	install, uninstall = flags(unicodeScript)
	require.False(t, install, "MySQL and the generator disagree on hashing multi-byte characters")
	require.False(t, uninstall)

	install, _ = flags(wrongApp)
	require.True(t, install, "a script published for another app doesn't count as this app's")

	install, uninstall = flags(changedAfterCutoff)
	require.False(t, install, "rows changed after the corpus cutoff keep the default")
	require.False(t, uninstall)

	install, uninstall = flags(substitutedUninstall)
	require.True(t, install, "the install script is still judged normally")
	require.False(t, uninstall, "a substituted uninstall script can't be judged, so the flag stays off")

	install, uninstall = flags(notMaintained)
	require.False(t, install)
	require.False(t, uninstall)

	// New rows default to not-edited.
	fresh := insertInstaller("Fresh", 0, foo, "fresh.pkg", adminInstall, adminUninstall)
	install, uninstall = flags(fresh)
	require.False(t, install)
	require.False(t, uninstall)
}

func serveScriptHashMaps(t *testing.T, install string, uninstall string) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch path.Base(r.URL.Path) {
		case installScriptHashMapFile:
			_, _ = w.Write([]byte(install))
		case uninstallScriptHashMapFile:
			_, _ = w.Write([]byte(uninstall))
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	t.Cleanup(srv.Close)

	restore := fmaScriptHashMapBaseURL
	t.Cleanup(func() { fmaScriptHashMapBaseURL = restore })
	fmaScriptHashMapBaseURL = srv.URL + "/"
}

func TestFetchScriptHashMapFails(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusInternalServerError)
	}))
	t.Cleanup(srv.Close)

	restore := fmaScriptHashMapBaseURL
	t.Cleanup(func() { fmaScriptHashMapBaseURL = restore })
	fmaScriptHashMapBaseURL = srv.URL + "/"

	_, _, err := fetchScriptHashMap(installScriptHashMapFile)
	require.ErrorContains(t, err, "HTTP status 500")
}

func TestScriptHashMapFiles(t *testing.T) {
	read := func(name string) (scriptHashMap, time.Time) {
		contents, err := os.ReadFile(filepath.Join("..", "..", "..", "..", "..", "tools", "software", "fma-script-hashes", name))
		require.NoError(t, err)
		hashes, toDate, err := parseScriptHashMap(string(contents))
		require.NoError(t, err)
		require.False(t, toDate.IsZero())
		require.NotEmpty(t, hashes)
		return hashes, toDate
	}

	install, installCutoff := read(installScriptHashMapFile)
	uninstall, uninstallCutoff := read(uninstallScriptHashMapFile)

	// both files come out of one run, so a mismatched cutoff means they were
	// regenerated separately and no longer describe the same history
	require.Equal(t, installCutoff, uninstallCutoff)

	// every line holds either a sha256 or the word "substituted". The generator writes
	// that word and this migration looks it up, and neither reads the other's copy of
	// it, so renaming one side has to fail here rather than in production.
	substituted := 0
	for _, hashes := range []scriptHashMap{install, uninstall} {
		for key := range hashes {
			hash, _, found := strings.Cut(key, " ")
			require.True(t, found)
			if len(hash) == 2*sha256.Size {
				continue
			}
			require.Equal(t, substitutedScriptMarker, hash)
			substituted++
		}
	}
	require.NotZero(t, substituted, "some uninstall scripts get substituted, so the word should appear")

	// every app publishes both scripts, so a slug in one file and not the other
	// means the generator dropped one kind for that app
	slugs := func(hashes scriptHashMap) map[string]struct{} {
		apps := map[string]struct{}{}
		for key := range hashes {
			_, slug, found := strings.Cut(key, " ")
			require.True(t, found)
			apps[slug] = struct{}{}
		}
		return apps
	}
	require.Equal(t, slugs(install), slugs(uninstall))
}

// A hash map that arrives truncated or malformed has to stop the migration, since
// carrying on would read every installer as unedited.
func TestParseScriptHashMapRejectsBadInput(t *testing.T) {
	const header = "# Generated by tools/software/fma-script-hashes. DO NOT EDIT.\n# to abcd1234 2026-08-01T00:00:00Z\n"

	for _, tc := range []struct {
		name     string
		contents string
		wantErr  string
	}{
		{"no header", "# Generated by tools/software/fma-script-hashes. DO NOT EDIT.", "too short"},
		{"header is not the cutoff line", "# Generated\n# from abcd1234\n", `expected a "# to <commit> <date>" header`},
		{"cutoff is not a date", "# Generated\n# to abcd1234 last-tuesday\n", "parsing cutoff"},
		{"entry missing its slug", header + "abc123\n", `unexpected line "abc123"`},
		{"entry with a spare field", header + "abc123 foo/darwin extra\n", "unexpected line"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			_, _, err := parseScriptHashMap(tc.contents)
			require.ErrorContains(t, err, tc.wantErr)
		})
	}

	hashes, cutoff, err := parseScriptHashMap(header + "abc123 foo/darwin\nabc123 bar/darwin\n")
	require.NoError(t, err)
	require.Equal(t, "2026-08-01T00:00:00Z", cutoff.Format(time.RFC3339))
	require.Len(t, hashes, 2)
	_, found := hashes["abc123 foo/darwin"]
	require.True(t, found)
}

func sha256Hex(contents string) string {
	sum := sha256.Sum256([]byte(contents))
	return hex.EncodeToString(sum[:])
}
