import React from "react";
import { Meta, StoryObj } from "@storybook/react";

import TooltipWrapper from ".";

import "../../index.scss";

const meta: Meta<typeof TooltipWrapper> = {
  component: TooltipWrapper,
  title: "Components/TooltipWrapper",
  argTypes: {
    position: {
      options: [
        "top",
        "top-start",
        "top-end",
        "right",
        "right-start",
        "right-end",
        "bottom",
        "bottom-start",
        "bottom-end",
        "left",
        "left-start",
        "left-end",
      ],
      control: "radio",
    },
  },
  decorators: [
    (Story) => (
      <div style={{ margin: "4rem 0" }}>
        <Story />
      </div>
    ),
  ],
};

export default meta;

type Story = StoryObj<typeof TooltipWrapper>;

export const Default: Story = {
  args: {
    tipContent: "This is an example tooltip.",
    children: "Example text",
  },
};

/** Medium prose that wraps to two lines. Balance evens the line widths so
 * neither has a hanging widow, and the tooltip shrinks to hug the widest
 * balanced line rather than sitting at `max-width`. */
export const BalancedTwoLines: Story = {
  args: {
    tipContent:
      "Bypassing is valid for a single login attempt and is tracked in audit logs.",
    children: "Two lines",
  },
};

/** Dense prose that wraps to three or four lines. Compare the tidiness of the
 * ragged right against a normal wrap. */
export const BalancedDensePassage: Story = {
  args: {
    tipContent:
      "When enabled, allows automatic cleanup of hosts that have not communicated with Fleet in the number of days specified.",
    children: "Dense passage",
  },
};

/** Opt out of balancing via `textBalanced={false}`. Rendered next to the
 * balanced version of the same content so the difference is visible. */
export const BalancedVsUnbalanced: Story = {
  render: () => (
    <div style={{ display: "flex", gap: "6rem", alignItems: "flex-start" }}>
      <TooltipWrapper
        tipContent="When enabled, allows automatic cleanup of hosts that have not communicated with Fleet in the number of days specified."
        textBalanced={false}
      >
        textBalanced=false
      </TooltipWrapper>
      <TooltipWrapper tipContent="When enabled, allows automatic cleanup of hosts that have not communicated with Fleet in the number of days specified.">
        textBalanced=true (default)
      </TooltipWrapper>
    </div>
  ),
};

/** The Fleet settings convention: main tooltip prose above, a single `<br />`,
 * and the `(Default: X)` annotation on its own line wrapped in `<i>`. Balance
 * runs on the prose above the hard break independently. */
export const BalancedWithDefaultFootnote: Story = {
  args: {
    tipContent: (
      <>
        When disabled, removes AI features such as pre-filling forms with
        descriptions generated by a large language model (LLM).
        <br />
        <i>
          (Default: <strong>On</strong>)
        </i>
      </>
    ),
    children: "With (Default:) footnote",
  },
};

/** Balance flows through nested inline elements (`<strong>`, `<em>`, `<b>`)
 * without breaking. Line rects still resolve correctly. */
export const BalancedWithNestedMarkup: Story = {
  args: {
    tipContent: (
      <>
        When enabled, preserves host activities after a wipe and re-enrollment.
        Currently only supported for company-owned (AB) Apple hosts.{" "}
        <strong>Delete activities &gt; Max activity age</strong> still applies.
      </>
    ),
    children: "With nested markup",
  },
};

/** Hovering any of these triggers should render NO tooltip — no empty
 * background flash, no arrow. Callers can pass a conditional `tipContent`
 * without gating on `disableTooltip` themselves. */
export const EmptyContentSuppressed: Story = {
  render: () => (
    <div style={{ display: "flex", gap: "4rem", alignItems: "flex-start" }}>
      <TooltipWrapper tipContent="">Empty string</TooltipWrapper>
      <TooltipWrapper tipContent={null}>Null</TooltipWrapper>
      <TooltipWrapper tipContent={undefined}>Undefined</TooltipWrapper>
      <TooltipWrapper tipContent={false && "hidden"}>
        Falsy conditional
      </TooltipWrapper>
      <TooltipWrapper tipContent="Populated, for contrast">
        Populated
      </TooltipWrapper>
    </div>
  ),
};

/** Structural `<br />`s (list separators) are respected as forced breaks —
 * balance runs within each segment rather than across the whole flow. */
export const BalancedWithForcedBreaks: Story = {
  args: {
    tipContent: (
      <>
        <b>Admin:</b> Alice, Bob, Charlie
        <br />
        <b>Maintainer:</b> Dana, Eli
        <br />
        <b>Observer:</b> Faye, Gil, Henry, Ida
      </>
    ),
    children: "With forced breaks",
  },
};
