#!/bin/bash

## DB Schema Dump
if [[ $DB_SCHEMA_DUMP ]]; then
  make dump-test-schema
  if [[ $(git diff-files --patch server/datastore/mysql/schema.sql server/mdm/android/mysql/schema.sql) ]]; then
    echo "❌ fail: uncommited changes in schema.sql"
    echo "please run 'make dump-test-schema' and commit the changes"
    exit 1
  fi
fi
