// Automatically generated by MockGen. DO NOT EDIT!
// Source: kolide/osquery.go

package mock

import (
	time "time"

	gomock "github.com/golang/mock/gomock"
	"github.com/kolide/kolide-ose/kolide"
)

// Mock of OsqueryStore interface
type MockOsqueryStore struct {
	ctrl     *gomock.Controller
	recorder *_MockOsqueryStoreRecorder
}

// Recorder for MockOsqueryStore (not exported)
type _MockOsqueryStoreRecorder struct {
	mock *MockOsqueryStore
}

func NewMockOsqueryStore(ctrl *gomock.Controller) *MockOsqueryStore {
	mock := &MockOsqueryStore{ctrl: ctrl}
	mock.recorder = &_MockOsqueryStoreRecorder{mock}
	return mock
}

func (_m *MockOsqueryStore) EXPECT() *_MockOsqueryStoreRecorder {
	return _m.recorder
}

func (_m *MockOsqueryStore) EnrollHost(uuid string, hostname string, ip string, platform string, nodeKeySize int) (*kolide.Host, error) {
	ret := _m.ctrl.Call(_m, "EnrollHost", uuid, hostname, ip, platform, nodeKeySize)
	ret0, _ := ret[0].(*kolide.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockOsqueryStoreRecorder) EnrollHost(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "EnrollHost", arg0, arg1, arg2, arg3, arg4)
}

func (_m *MockOsqueryStore) AuthenticateHost(nodeKey string) (*kolide.Host, error) {
	ret := _m.ctrl.Call(_m, "AuthenticateHost", nodeKey)
	ret0, _ := ret[0].(*kolide.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockOsqueryStoreRecorder) AuthenticateHost(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AuthenticateHost", arg0)
}

func (_m *MockOsqueryStore) SaveHost(host *kolide.Host) error {
	ret := _m.ctrl.Call(_m, "SaveHost", host)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockOsqueryStoreRecorder) SaveHost(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SaveHost", arg0)
}

func (_m *MockOsqueryStore) MarkHostSeen(host *kolide.Host, t time.Time) error {
	ret := _m.ctrl.Call(_m, "MarkHostSeen", host, t)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockOsqueryStoreRecorder) MarkHostSeen(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MarkHostSeen", arg0, arg1)
}

func (_m *MockOsqueryStore) LabelQueriesForHost(host *kolide.Host, cutoff time.Time) (map[string]string, error) {
	ret := _m.ctrl.Call(_m, "LabelQueriesForHost", host, cutoff)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockOsqueryStoreRecorder) LabelQueriesForHost(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "LabelQueriesForHost", arg0, arg1)
}

func (_m *MockOsqueryStore) RecordLabelQueryExecutions(host *kolide.Host, results map[string]bool, t time.Time) error {
	ret := _m.ctrl.Call(_m, "RecordLabelQueryExecutions", host, results, t)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockOsqueryStoreRecorder) RecordLabelQueryExecutions(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RecordLabelQueryExecutions", arg0, arg1, arg2)
}

func (_m *MockOsqueryStore) NewQuery(query *kolide.Query) error {
	ret := _m.ctrl.Call(_m, "NewQuery", query)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockOsqueryStoreRecorder) NewQuery(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "NewQuery", arg0)
}

func (_m *MockOsqueryStore) SaveQuery(query *kolide.Query) error {
	ret := _m.ctrl.Call(_m, "SaveQuery", query)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockOsqueryStoreRecorder) SaveQuery(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SaveQuery", arg0)
}

func (_m *MockOsqueryStore) DeleteQuery(query *kolide.Query) error {
	ret := _m.ctrl.Call(_m, "DeleteQuery", query)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockOsqueryStoreRecorder) DeleteQuery(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteQuery", arg0)
}

func (_m *MockOsqueryStore) Query(id uint) (*kolide.Query, error) {
	ret := _m.ctrl.Call(_m, "Query", id)
	ret0, _ := ret[0].(*kolide.Query)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockOsqueryStoreRecorder) Query(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Query", arg0)
}

func (_m *MockOsqueryStore) Queries() ([]*kolide.Query, error) {
	ret := _m.ctrl.Call(_m, "Queries")
	ret0, _ := ret[0].([]*kolide.Query)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockOsqueryStoreRecorder) Queries() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Queries")
}

func (_m *MockOsqueryStore) NewLabel(label *kolide.Label) error {
	ret := _m.ctrl.Call(_m, "NewLabel", label)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockOsqueryStoreRecorder) NewLabel(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "NewLabel", arg0)
}

func (_m *MockOsqueryStore) NewPack(pack *kolide.Pack) error {
	ret := _m.ctrl.Call(_m, "NewPack", pack)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockOsqueryStoreRecorder) NewPack(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "NewPack", arg0)
}

func (_m *MockOsqueryStore) SavePack(pack *kolide.Pack) error {
	ret := _m.ctrl.Call(_m, "SavePack", pack)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockOsqueryStoreRecorder) SavePack(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SavePack", arg0)
}

func (_m *MockOsqueryStore) DeletePack(pack *kolide.Pack) error {
	ret := _m.ctrl.Call(_m, "DeletePack", pack)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockOsqueryStoreRecorder) DeletePack(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeletePack", arg0)
}

func (_m *MockOsqueryStore) Pack(id uint) (*kolide.Pack, error) {
	ret := _m.ctrl.Call(_m, "Pack", id)
	ret0, _ := ret[0].(*kolide.Pack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockOsqueryStoreRecorder) Pack(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Pack", arg0)
}

func (_m *MockOsqueryStore) Packs() ([]*kolide.Pack, error) {
	ret := _m.ctrl.Call(_m, "Packs")
	ret0, _ := ret[0].([]*kolide.Pack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockOsqueryStoreRecorder) Packs() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Packs")
}

func (_m *MockOsqueryStore) AddQueryToPack(query *kolide.Query, pack *kolide.Pack) error {
	ret := _m.ctrl.Call(_m, "AddQueryToPack", query, pack)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockOsqueryStoreRecorder) AddQueryToPack(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AddQueryToPack", arg0, arg1)
}

func (_m *MockOsqueryStore) GetQueriesInPack(pack *kolide.Pack) ([]*kolide.Query, error) {
	ret := _m.ctrl.Call(_m, "GetQueriesInPack", pack)
	ret0, _ := ret[0].([]*kolide.Query)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockOsqueryStoreRecorder) GetQueriesInPack(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetQueriesInPack", arg0)
}

func (_m *MockOsqueryStore) RemoveQueryFromPack(query *kolide.Query, pack *kolide.Pack) error {
	ret := _m.ctrl.Call(_m, "RemoveQueryFromPack", query, pack)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockOsqueryStoreRecorder) RemoveQueryFromPack(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RemoveQueryFromPack", arg0, arg1)
}
