// Automatically generated by mockimpl. DO NOT EDIT!

package mock

import (
	"context"
	"crypto/x509"
	"sync"

	"github.com/fleetdm/fleet/v4/server/fleet"
)

var _ fleet.SCEPEnrollmentClient = (*SCEPEnrollmentClient)(nil)

type GetCertificateFunc func(ctx context.Context, url string, csr *x509.CertificateRequest) (*x509.Certificate, error)

type SCEPEnrollmentClient struct {
	GetCertificateFunc        GetCertificateFunc
	GetCertificateFuncInvoked bool

	mu sync.Mutex
}

func (c *SCEPEnrollmentClient) GetCertificate(ctx context.Context, url string, csr *x509.CertificateRequest) (*x509.Certificate, error) {
	c.mu.Lock()
	c.GetCertificateFuncInvoked = true
	c.mu.Unlock()
	return c.GetCertificateFunc(ctx, url, csr)
}
