variable "prefix" {}
variable "dynamodb_table" {}
variable "vpc" {}
variable "remote_state" {}
variable "mysql_secret" {}
variable "mysql_secret_kms" {}
variable "eks_cluster" {}
variable "redis_cluster" {}
variable "alb_listener" {}
variable "base_domain" {}
variable "ecs_cluster" {}
variable "kms_key" {}
