// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Branch is one branch in the list view.
 */
export class Branch {
    "name": string;
    "is_current": boolean;
    "is_local": boolean;
    "is_remote": boolean;
    "last_commit": CommitInfo | null;

    /** Creates a new Branch instance. */
    constructor($$source: Partial<Branch> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("is_current" in $$source)) {
            this["is_current"] = false;
        }
        if (!("is_local" in $$source)) {
            this["is_local"] = false;
        }
        if (!("is_remote" in $$source)) {
            this["is_remote"] = false;
        }
        if (!("last_commit" in $$source)) {
            this["last_commit"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Branch instance from a string or object.
     */
    static createFrom($$source: any = {}): Branch {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("last_commit" in $$parsedSource) {
            $$parsedSource["last_commit"] = $$createField4_0($$parsedSource["last_commit"]);
        }
        return new Branch($$parsedSource as Partial<Branch>);
    }
}

/**
 * BranchStatus is the working-tree status of the current branch.
 */
export class BranchStatus {
    "branch": string;
    "clean": boolean;
    "ahead": number;
    "behind": number;
    "modified": FileChange[];
    "last_commit": CommitInfo | null;

    /** Creates a new BranchStatus instance. */
    constructor($$source: Partial<BranchStatus> = {}) {
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("clean" in $$source)) {
            this["clean"] = false;
        }
        if (!("ahead" in $$source)) {
            this["ahead"] = 0;
        }
        if (!("behind" in $$source)) {
            this["behind"] = 0;
        }
        if (!("modified" in $$source)) {
            this["modified"] = [];
        }
        if (!("last_commit" in $$source)) {
            this["last_commit"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): BranchStatus {
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("modified" in $$parsedSource) {
            $$parsedSource["modified"] = $$createField4_0($$parsedSource["modified"]);
        }
        if ("last_commit" in $$parsedSource) {
            $$parsedSource["last_commit"] = $$createField5_0($$parsedSource["last_commit"]);
        }
        return new BranchStatus($$parsedSource as Partial<BranchStatus>);
    }
}

/**
 * CommitInfo summarizes a single commit.
 */
export class CommitInfo {
    "sha": string;
    "subject": string;
    "author": string;
    "time_ago": string;

    /** Creates a new CommitInfo instance. */
    constructor($$source: Partial<CommitInfo> = {}) {
        if (!("sha" in $$source)) {
            this["sha"] = "";
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("time_ago" in $$source)) {
            this["time_ago"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CommitInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitInfo($$parsedSource as Partial<CommitInfo>);
    }
}

/**
 * FileChange is one entry from `git status --porcelain`.
 */
export class FileChange {
    "status": string;
    "path": string;

    /** Creates a new FileChange instance. */
    constructor($$source: Partial<FileChange> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileChange instance from a string or object.
     */
    static createFrom($$source: any = {}): FileChange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileChange($$parsedSource as Partial<FileChange>);
    }
}

// Private type creation functions
const $$createType0 = CommitInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = FileChange.createFrom;
const $$createType3 = $Create.Array($$createType2);
