FROM --platform=linux/amd64 golang:1.20.7-bookworm@sha256:3d0878a1192d931876c9f21feb06beaf2771d2e53d6a3092093cf84b9205c1c1
LABEL maintainer="Fleet Developers"

RUN apt-get update && apt-get install -y \
	gcc \
	libgtk-3-dev \
	libayatana-appindicator3-dev \
	&& rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/src/fleet
RUN mkdir -p /output

WORKDIR /usr/src/fleet

COPY orbit ./orbit
COPY server ./server
COPY ee ./ee
COPY pkg ./pkg
COPY go.mod go.sum ./

CMD /bin/bash
