/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, April 28, 2021 at 2:51:09 PM British Summer Time
* Operating System: Version 11.3 (Build 20E232)
* Image Source: /System/Library/PrivateFrameworks/SoftwareUpdate.framework/Versions/A/SoftwareUpdate
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString, NSArray, SUMajorProduct, NSDate, NSDictionary, NSURL, NSData, NSAttributedString;

@interface SUUpdateProduct : NSObject <NSSecureCoding> {

	char _allowedToUseInstallLater;
	char _shouldAuthenticateReboot;
	char _shouldLaunchFirstLoginOptimization;
	char _isABaseSystemUpdate;
	char _isMajorOSUpdate;
	char _isMajorOSUpdateInternal;
	char _adminDeferred;
	char _doItLaterUpdateAndNowIsLater;
	char _isFirmwareUpdate;
	char _autoUpdateEligible;
	char _showPostInstallNotification;
	int _action;
	NSString* _title;
	NSString* _versionString;
	NSString* _currentLocalization;
	NSString* _productKey;
	long long _serverState;
	long long _type;
	NSArray* _applicationIdentifiersToClose;
	NSArray* _tags;
	id _auxInfo;
	NSString* _identifierForProductLabel;
	NSString* _versionForProductLabel;
	NSString* _serverMetadataURL;
	SUMajorProduct* _majorProduct;
	NSDate* _adminDeferralDate;
	NSDictionary* _matchingDictionary;
	NSDictionary* _extraInfo;
	NSArray* _packageIdentifiersToInstall;
	long long _downloadSize;
	NSString* _productType;
	NSString* _productBuildVersion;
	NSString* _productVersion;
	NSDate* _postDate;
	NSDate* _deferredEnablementDate;
	NSDictionary* _updateInfo;
	long long _shouldAutoInstallWithDelayInHours;
	NSString* _customCriticalNotificationTitle;
	NSString* _customCriticalNotificationText;
	NSString* _customTitleForPostInstallNotification;
	NSString* _customTextForPostInstallNotification;
	NSURL* _customURLForPostInstallNotification;
	NSData* _longDescriptionRTFData;
	NSData* _firmwareWarningRTFData;
	NSData* _licenseAgreementRTFData;
	NSAttributedString* _cachedLongDescription;
	NSAttributedString* _cachedFirmwareWarning;
	NSAttributedString* _cachedLicenseAgreement;

}

@property (retain) NSData * longDescriptionRTFData;                                        //@synthesize longDescriptionRTFData=_longDescriptionRTFData - In the implementation block
@property (retain) NSData * firmwareWarningRTFData;                                        //@synthesize firmwareWarningRTFData=_firmwareWarningRTFData - In the implementation block
@property (retain) NSData * licenseAgreementRTFData;                                       //@synthesize licenseAgreementRTFData=_licenseAgreementRTFData - In the implementation block
@property (retain) NSAttributedString * cachedLongDescription;                             //@synthesize cachedLongDescription=_cachedLongDescription - In the implementation block
@property (retain) NSAttributedString * cachedFirmwareWarning;                             //@synthesize cachedFirmwareWarning=_cachedFirmwareWarning - In the implementation block
@property (retain) NSAttributedString * cachedLicenseAgreement;                            //@synthesize cachedLicenseAgreement=_cachedLicenseAgreement - In the implementation block
@property (retain,readonly) NSString * title;                                              //@synthesize title=_title - In the implementation block
@property (retain,readonly) NSString * versionString;                                      //@synthesize versionString=_versionString - In the implementation block
@property (readonly) int action;                                                           //@synthesize action=_action - In the implementation block
@property (retain,readonly) NSString * currentLocalization;                                //@synthesize currentLocalization=_currentLocalization - In the implementation block
@property (retain,readonly) NSAttributedString * longDescription; 
@property (retain,readonly) NSAttributedString * firmwareWarning; 
@property (retain,readonly) NSAttributedString * licenseAgreement; 
@property (retain,readonly) NSString * productKey;                                         //@synthesize productKey=_productKey - In the implementation block
@property (readonly) long long serverState;                                                //@synthesize serverState=_serverState - In the implementation block
@property (readonly) long long type;                                                       //@synthesize type=_type - In the implementation block
@property (retain,readonly) NSArray * applicationIdentifiersToClose;                       //@synthesize applicationIdentifiersToClose=_applicationIdentifiersToClose - In the implementation block
@property (retain,readonly) NSArray * tags;                                                //@synthesize tags=_tags - In the implementation block
@property (retain,readonly) id auxInfo;                                                    //@synthesize auxInfo=_auxInfo - In the implementation block
@property (retain,readonly) NSString * identifierForProductLabel;                          //@synthesize identifierForProductLabel=_identifierForProductLabel - In the implementation block
@property (retain,readonly) NSString * versionForProductLabel;                             //@synthesize versionForProductLabel=_versionForProductLabel - In the implementation block
@property (retain,readonly) NSString * serverMetadataURL;                                  //@synthesize serverMetadataURL=_serverMetadataURL - In the implementation block
@property (readonly) char allowedToUseInstallLater;                                        //@synthesize allowedToUseInstallLater=_allowedToUseInstallLater - In the implementation block
@property (readonly) char shouldAuthenticateReboot;                                        //@synthesize shouldAuthenticateReboot=_shouldAuthenticateReboot - In the implementation block
@property (readonly) char shouldLaunchFirstLoginOptimization;                              //@synthesize shouldLaunchFirstLoginOptimization=_shouldLaunchFirstLoginOptimization - In the implementation block
@property (assign) char isABaseSystemUpdate;                                               //@synthesize isABaseSystemUpdate=_isABaseSystemUpdate - In the implementation block
@property (readonly) char isMajorOSUpdate;                                                 //@synthesize isMajorOSUpdate=_isMajorOSUpdate - In the implementation block
@property (readonly) char isMajorOSUpdateInternal;                                         //@synthesize isMajorOSUpdateInternal=_isMajorOSUpdateInternal - In the implementation block
@property (retain,readonly) SUMajorProduct * majorProduct;                                 //@synthesize majorProduct=_majorProduct - In the implementation block
@property (readonly) char adminDeferred;                                                   //@synthesize adminDeferred=_adminDeferred - In the implementation block
@property (retain,readonly) NSDate * adminDeferralDate;                                    //@synthesize adminDeferralDate=_adminDeferralDate - In the implementation block
@property (retain,readonly) NSDictionary * matchingDictionary;                             //@synthesize matchingDictionary=_matchingDictionary - In the implementation block
@property (retain,readonly) NSDictionary * extraInfo;                                      //@synthesize extraInfo=_extraInfo - In the implementation block
@property (readonly) NSArray * packageIdentifiersToInstall;                                //@synthesize packageIdentifiersToInstall=_packageIdentifiersToInstall - In the implementation block
@property (readonly) long long downloadSize;                                               //@synthesize downloadSize=_downloadSize - In the implementation block
@property (assign) char doItLaterUpdateAndNowIsLater;                                      //@synthesize doItLaterUpdateAndNowIsLater=_doItLaterUpdateAndNowIsLater - In the implementation block
@property (assign) char isFirmwareUpdate;                                                  //@synthesize isFirmwareUpdate=_isFirmwareUpdate - In the implementation block
@property (readonly) NSString * productType;                                               //@synthesize productType=_productType - In the implementation block
@property (readonly) NSString * productBuildVersion;                                       //@synthesize productBuildVersion=_productBuildVersion - In the implementation block
@property (readonly) NSString * productVersion;                                            //@synthesize productVersion=_productVersion - In the implementation block
@property (getter=isAutoUpdateEligible,readonly) char autoUpdateEligible;                  //@synthesize autoUpdateEligible=_autoUpdateEligible - In the implementation block
@property (readonly) NSDate * postDate;                                                    //@synthesize postDate=_postDate - In the implementation block
@property (readonly) NSDate * deferredEnablementDate;                                      //@synthesize deferredEnablementDate=_deferredEnablementDate - In the implementation block
@property (readonly) NSDictionary * updateInfo;                                            //@synthesize updateInfo=_updateInfo - In the implementation block
@property (readonly) long long shouldAutoInstallWithDelayInHours;                          //@synthesize shouldAutoInstallWithDelayInHours=_shouldAutoInstallWithDelayInHours - In the implementation block
@property (retain,readonly) NSString * customCriticalNotificationTitle;                    //@synthesize customCriticalNotificationTitle=_customCriticalNotificationTitle - In the implementation block
@property (retain,readonly) NSString * customCriticalNotificationText;                     //@synthesize customCriticalNotificationText=_customCriticalNotificationText - In the implementation block
@property (readonly) char showPostInstallNotification;                                     //@synthesize showPostInstallNotification=_showPostInstallNotification - In the implementation block
@property (retain,readonly) NSString * customTitleForPostInstallNotification;              //@synthesize customTitleForPostInstallNotification=_customTitleForPostInstallNotification - In the implementation block
@property (retain,readonly) NSString * customTextForPostInstallNotification;               //@synthesize customTextForPostInstallNotification=_customTextForPostInstallNotification - In the implementation block
@property (retain,readonly) NSURL * customURLForPostInstallNotification;                   //@synthesize customURLForPostInstallNotification=_customURLForPostInstallNotification - In the implementation block
+(id)stringForUpdateType:(long long)arg1 ;
+(id)stringForUpdateState:(long long)arg1 ;
+(char)supportsSecureCoding;
-(NSArray *)packageIdentifiersToInstall;
-(id)initWithSUProduct:(id)arg1 ;
-(id)getObjectFromExtendedMetaInfoForKey:(id)arg1 ;
-(id)initWithProductKey:(id)arg1 title:(id)arg2 versionString:(id)arg3 longDescription:(id)arg4 ;
-(void)setDoItLaterUpdateAndNowIsLater:(char)arg1 ;
-(NSString *)identifierForProductLabel;
-(NSString *)versionForProductLabel;
-(NSData *)longDescriptionRTFData;
-(NSData *)licenseAgreementRTFData;
-(NSData *)firmwareWarningRTFData;
-(NSAttributedString *)cachedLongDescription;
-(void)setCachedLongDescription:(NSAttributedString *)arg1 ;
-(NSAttributedString *)cachedFirmwareWarning;
-(void)setCachedFirmwareWarning:(NSAttributedString *)arg1 ;
-(NSAttributedString *)cachedLicenseAgreement;
-(void)setCachedLicenseAgreement:(NSAttributedString *)arg1 ;
-(void)setIsABaseSystemUpdate:(char)arg1 ;
-(void)setLongDescriptionRTFData:(NSData *)arg1 ;
-(void)setFirmwareWarningRTFData:(NSData *)arg1 ;
-(void)setLicenseAgreementRTFData:(NSData *)arg1 ;
-(void)dealloc;
-(char)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)debugDescription;
-(void)encodeWithCoder:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(long long)type;
-(int)action;
-(NSArray *)tags;
-(NSString *)title;
-(NSString *)versionString;
-(NSString *)productVersion;
-(NSString *)productBuildVersion;
-(NSString *)productType;
-(long long)serverState;
-(NSAttributedString *)longDescription;
-(long long)downloadSize;
-(id)auxInfo;
-(NSString *)productKey;
-(char)shouldLaunchFirstLoginOptimization;
-(char)doItLaterUpdateAndNowIsLater;
-(char)isABaseSystemUpdate;
-(char)isMajorOSUpdate;
-(char)shouldAuthenticateReboot;
-(char)allowedToUseInstallLater;
-(char)isAutoUpdateEligible;
-(char)isMajorOSUpdateInternal;
-(NSDictionary *)extraInfo;
-(SUMajorProduct *)majorProduct;
-(NSDate *)postDate;
-(NSArray *)applicationIdentifiersToClose;
-(NSAttributedString *)licenseAgreement;
-(NSAttributedString *)firmwareWarning;
-(NSString *)currentLocalization;
-(char)showPostInstallNotification;
-(NSString *)customTitleForPostInstallNotification;
-(NSString *)customTextForPostInstallNotification;
-(NSURL *)customURLForPostInstallNotification;
-(char)isFirmwareUpdate;
-(NSString *)serverMetadataURL;
-(NSString *)customCriticalNotificationTitle;
-(NSString *)customCriticalNotificationText;
-(long long)shouldAutoInstallWithDelayInHours;
-(char)adminDeferred;
-(NSDate *)deferredEnablementDate;
-(void)setIsFirmwareUpdate:(char)arg1 ;
-(NSDate *)adminDeferralDate;
-(id)updateLabel;
-(NSDictionary *)updateInfo;
-(NSDictionary *)matchingDictionary;
@end

