// Automatically generated by mockimpl. DO NOT EDIT!

package mock

import "github.com/fleetdm/fleet/server/kolide"

var _ kolide.AppConfigStore = (*AppConfigStore)(nil)

type NewAppConfigFunc func(info *kolide.AppConfig) (*kolide.AppConfig, error)

type AppConfigFunc func() (*kolide.AppConfig, error)

type SaveAppConfigFunc func(info *kolide.AppConfig) error

type VerifyEnrollSecretFunc func(secret string) (*kolide.EnrollSecret, error)

type ApplyEnrollSecretsFunc func(treamID *uint, secrets []*kolide.EnrollSecret) error

type GetEnrollSecretsFunc func(teamID *uint) ([]*kolide.EnrollSecret, error)

type AppConfigStore struct {
	NewAppConfigFunc        NewAppConfigFunc
	NewAppConfigFuncInvoked bool

	AppConfigFunc        AppConfigFunc
	AppConfigFuncInvoked bool

	SaveAppConfigFunc        SaveAppConfigFunc
	SaveAppConfigFuncInvoked bool

	VerifyEnrollSecretFunc        VerifyEnrollSecretFunc
	VerifyEnrollSecretFuncInvoked bool

	ApplyEnrollSecretsFunc        ApplyEnrollSecretsFunc
	ApplyEnrollSecretsFuncInvoked bool

	GetEnrollSecretsFunc        GetEnrollSecretsFunc
	GetEnrollSecretsFuncInvoked bool
}

func (s *AppConfigStore) NewAppConfig(info *kolide.AppConfig) (*kolide.AppConfig, error) {
	s.NewAppConfigFuncInvoked = true
	return s.NewAppConfigFunc(info)
}

func (s *AppConfigStore) AppConfig() (*kolide.AppConfig, error) {
	s.AppConfigFuncInvoked = true
	return s.AppConfigFunc()
}

func (s *AppConfigStore) SaveAppConfig(info *kolide.AppConfig) error {
	s.SaveAppConfigFuncInvoked = true
	return s.SaveAppConfigFunc(info)
}

func (s *AppConfigStore) VerifyEnrollSecret(secret string) (*kolide.EnrollSecret, error) {
	s.VerifyEnrollSecretFuncInvoked = true
	return s.VerifyEnrollSecretFunc(secret)
}

func (s *AppConfigStore) ApplyEnrollSecrets(teamID *uint, secrets []*kolide.EnrollSecret) error {
	s.ApplyEnrollSecretsFuncInvoked = true
	return s.ApplyEnrollSecretsFunc(teamID, secrets)
}

func (s *AppConfigStore) GetEnrollSecrets(teamID *uint) ([]*kolide.EnrollSecret, error) {
	s.GetEnrollSecretsFuncInvoked = true
	return s.GetEnrollSecretsFunc(teamID)
}
