// Automatically generated by mockimpl. DO NOT EDIT!

package mock

import "github.com/kolide/fleet/server/kolide"

var _ kolide.DecoratorStore = (*DecoratorStore)(nil)

type NewDecoratorFunc func(decorator *kolide.Decorator, opts ...kolide.OptionalArg) (*kolide.Decorator, error)

type DeleteDecoratorFunc func(id uint) error

type DecoratorFunc func(id uint) (*kolide.Decorator, error)

type ListDecoratorsFunc func(opts ...kolide.OptionalArg) ([]*kolide.Decorator, error)

type SaveDecoratorFunc func(dec *kolide.Decorator, opts ...kolide.OptionalArg) error

type DecoratorStore struct {
	NewDecoratorFunc        NewDecoratorFunc
	NewDecoratorFuncInvoked bool

	DeleteDecoratorFunc        DeleteDecoratorFunc
	DeleteDecoratorFuncInvoked bool

	DecoratorFunc        DecoratorFunc
	DecoratorFuncInvoked bool

	ListDecoratorsFunc        ListDecoratorsFunc
	ListDecoratorsFuncInvoked bool

	SaveDecoratorFunc        SaveDecoratorFunc
	SaveDecoratorFuncInvoked bool
}

func (s *DecoratorStore) NewDecorator(decorator *kolide.Decorator, opts ...kolide.OptionalArg) (*kolide.Decorator, error) {
	s.NewDecoratorFuncInvoked = true
	return s.NewDecoratorFunc(decorator, opts...)
}

func (s *DecoratorStore) DeleteDecorator(id uint) error {
	s.DeleteDecoratorFuncInvoked = true
	return s.DeleteDecoratorFunc(id)
}

func (s *DecoratorStore) Decorator(id uint) (*kolide.Decorator, error) {
	s.DecoratorFuncInvoked = true
	return s.DecoratorFunc(id)
}

func (s *DecoratorStore) ListDecorators(opts ...kolide.OptionalArg) ([]*kolide.Decorator, error) {
	s.ListDecoratorsFuncInvoked = true
	return s.ListDecoratorsFunc(opts...)
}

func (s *DecoratorStore) SaveDecorator(dec *kolide.Decorator, opts ...kolide.OptionalArg) error {
	s.SaveDecoratorFuncInvoked = true
	return s.SaveDecoratorFunc(dec, opts...)
}
