// Automatically generated by mockimpl. DO NOT EDIT!

package mock

import "github.com/kolide/fleet/server/kolide"

var _ kolide.FileIntegrityMonitoringStore = (*FileIntegrityMonitoringStore)(nil)

type NewFIMSectionFunc func(path *kolide.FIMSection, opts ...kolide.OptionalArg) (*kolide.FIMSection, error)

type FIMSectionsFunc func() (kolide.FIMSections, error)

type ClearFIMSectionsFunc func() error

type FileIntegrityMonitoringStore struct {
	NewFIMSectionFunc        NewFIMSectionFunc
	NewFIMSectionFuncInvoked bool

	FIMSectionsFunc        FIMSectionsFunc
	FIMSectionsFuncInvoked bool

	ClearFIMSectionsFunc        ClearFIMSectionsFunc
	ClearFIMSectionsFuncInvoked bool
}

func (s *FileIntegrityMonitoringStore) NewFIMSection(path *kolide.FIMSection, opts ...kolide.OptionalArg) (*kolide.FIMSection, error) {
	s.NewFIMSectionFuncInvoked = true
	return s.NewFIMSectionFunc(path, opts...)
}

func (s *FileIntegrityMonitoringStore) FIMSections() (kolide.FIMSections, error) {
	s.FIMSectionsFuncInvoked = true
	return s.FIMSectionsFunc()
}

func (s *FileIntegrityMonitoringStore) ClearFIMSections() error {
	s.ClearFIMSectionsFuncInvoked = true
	return s.ClearFIMSectionsFunc()
}
