// Automatically generated by mockimpl. DO NOT EDIT!

package mock

import "github.com/fleetdm/fleet/v4/server/fleet"

var _ fleet.InviteStore = (*InviteStore)(nil)

type NewInviteFunc func(i *fleet.Invite) (*fleet.Invite, error)

type ListInvitesFunc func(opt fleet.ListOptions) ([]*fleet.Invite, error)

type InviteFunc func(id uint) (*fleet.Invite, error)

type InviteByEmailFunc func(email string) (*fleet.Invite, error)

type InviteByTokenFunc func(token string) (*fleet.Invite, error)

type DeleteInviteFunc func(id uint) error

type InviteStore struct {
	NewInviteFunc        NewInviteFunc
	NewInviteFuncInvoked bool

	ListInvitesFunc        ListInvitesFunc
	ListInvitesFuncInvoked bool

	InviteFunc        InviteFunc
	InviteFuncInvoked bool

	InviteByEmailFunc        InviteByEmailFunc
	InviteByEmailFuncInvoked bool

	InviteByTokenFunc        InviteByTokenFunc
	InviteByTokenFuncInvoked bool

	DeleteInviteFunc        DeleteInviteFunc
	DeleteInviteFuncInvoked bool
}

func (s *InviteStore) NewInvite(i *fleet.Invite) (*fleet.Invite, error) {
	s.NewInviteFuncInvoked = true
	return s.NewInviteFunc(i)
}

func (s *InviteStore) ListInvites(opt fleet.ListOptions) ([]*fleet.Invite, error) {
	s.ListInvitesFuncInvoked = true
	return s.ListInvitesFunc(opt)
}

func (s *InviteStore) Invite(id uint) (*fleet.Invite, error) {
	s.InviteFuncInvoked = true
	return s.InviteFunc(id)
}

func (s *InviteStore) InviteByEmail(email string) (*fleet.Invite, error) {
	s.InviteByEmailFuncInvoked = true
	return s.InviteByEmailFunc(email)
}

func (s *InviteStore) InviteByToken(token string) (*fleet.Invite, error) {
	s.InviteByTokenFuncInvoked = true
	return s.InviteByTokenFunc(token)
}

func (s *InviteStore) DeleteInvite(id uint) error {
	s.DeleteInviteFuncInvoked = true
	return s.DeleteInviteFunc(id)
}
