// Automatically generated by mockimpl. DO NOT EDIT!

package mock

import "github.com/kolide/fleet/server/kolide"

var _ kolide.CarveStore = (*CarveStore)(nil)

type NewCarveFunc func(c *kolide.CarveMetadata) (*kolide.CarveMetadata, error)

type ListCarvesFunc func(opt kolide.ListOptions) ([]*kolide.CarveMetadata, error)

type CarveBySessionIdFunc func(sessionId string) (*kolide.CarveMetadata, error)

type NewBlockFunc func(metadataId int64, blockId int64, data []byte) error

type GetBlockFunc func(metadataId int64, blockId int64) ([]byte, error)

type CarveStore struct {
	NewCarveFunc        NewCarveFunc
	NewCarveFuncInvoked bool

	ListCarvesFunc        ListCarvesFunc
	ListCarvesFuncInvoked bool

	CarveBySessionIdFunc        CarveBySessionIdFunc
	CarveBySessionIdFuncInvoked bool

	NewBlockFunc        NewBlockFunc
	NewBlockFuncInvoked bool

	GetBlockFunc        GetBlockFunc
	GetBlockFuncInvoked bool
}

func (s *CarveStore) NewCarve(c *kolide.CarveMetadata) (*kolide.CarveMetadata, error) {
	s.NewCarveFuncInvoked = true
	return s.NewCarveFunc(c)
}

func (s *CarveStore) ListCarves(opt kolide.ListOptions) ([]*kolide.CarveMetadata, error) {
	s.ListCarvesFuncInvoked = true
	return s.ListCarvesFunc(opt)
}

func (s *CarveStore) CarveBySessionId(sessionId string) (*kolide.CarveMetadata, error) {
	s.CarveBySessionIdFuncInvoked = true
	return s.CarveBySessionIdFunc(sessionId)
}

func (s *CarveStore) NewBlock(metadataId int64, blockId int64, data []byte) error {
	s.NewBlockFuncInvoked = true
	return s.NewBlockFunc(metadataId, blockId, data)
}

func (s *CarveStore) GetBlock(metadataId int64, blockId int64) ([]byte, error) {
	s.GetBlockFuncInvoked = true
	return s.GetBlockFunc(metadataId, blockId)
}
