// Automatically generated by mockimpl. DO NOT EDIT!

package mock

import (
	"sync"

	"github.com/fleetdm/fleet/v4/server/fleet"
)

var _ fleet.SoftwareStore = (*SoftwareStore)(nil)

type SaveHostSoftwareFunc func(host *fleet.Host) error

type LoadHostSoftwareFunc func(host *fleet.Host) error

type AllSoftwareIteratorFunc func() (fleet.SoftwareIterator, error)

type AddCPEForSoftwareFunc func(software fleet.Software, cpe string) error

type AllCPEsFunc func() ([]string, error)

type BulkInsertCVEsFunc func(cves *sync.Map) error

type SoftwareStore struct {
	SaveHostSoftwareFunc        SaveHostSoftwareFunc
	SaveHostSoftwareFuncInvoked bool

	LoadHostSoftwareFunc        LoadHostSoftwareFunc
	LoadHostSoftwareFuncInvoked bool

	AllSoftwareIteratorFunc        AllSoftwareIteratorFunc
	AllSoftwareIteratorFuncInvoked bool

	AddCPEForSoftwareFunc        AddCPEForSoftwareFunc
	AddCPEForSoftwareFuncInvoked bool

	AllCPEsFunc        AllCPEsFunc
	AllCPEsFuncInvoked bool

	BulkInsertCVEsFunc        BulkInsertCVEsFunc
	BulkInsertCVEsFuncInvoked bool
}

func (s *SoftwareStore) AllSoftwareWithoutCPEIterator() (fleet.SoftwareIterator, error) {
	s.AllSoftwareIteratorFuncInvoked = true
	return s.AllSoftwareIteratorFunc()
}

func (s *SoftwareStore) SaveHostSoftware(host *fleet.Host) error {
	s.SaveHostSoftwareFuncInvoked = true
	return s.SaveHostSoftwareFunc(host)
}

func (s *SoftwareStore) LoadHostSoftware(host *fleet.Host) error {
	s.LoadHostSoftwareFuncInvoked = true
	return s.LoadHostSoftwareFunc(host)
}

func (s *SoftwareStore) AddCPEForSoftware(software fleet.Software, cpe string) error {
	s.AddCPEForSoftwareFuncInvoked = true
	return s.AddCPEForSoftwareFunc(software, cpe)
}

func (s *SoftwareStore) AllCPEs() ([]string, error) {
	s.AllCPEsFuncInvoked = true
	return s.AllCPEsFunc()
}

func (s *SoftwareStore) BulkInsertCVEs(cves *sync.Map) error {
	s.BulkInsertCVEsFuncInvoked = true
	return s.BulkInsertCVEsFunc(cves)
}
