// Automatically generated by mockimpl. DO NOT EDIT!

package mock

import "github.com/fleetdm/fleet/v4/server/fleet"

var _ fleet.ActivitiesStore = (*ActivitiesStore)(nil)

type NewActivityFunc func(user *fleet.User, activityType string, details *map[string]interface{}) error

type ActivitiesStore struct {
	NewActivityFunc        NewActivityFunc
	NewActivityFuncInvoked bool
}

func (s *ActivitiesStore) NewActivity(user *fleet.User, activityType string, details *map[string]interface{}) error {
	s.NewActivityFuncInvoked = true
	return s.NewActivityFunc(user, activityType, details)
}
