// Automatically generated by mockimpl. DO NOT EDIT!

package mock

import "github.com/kolide/kolide/server/kolide"

var _ kolide.IdentityProviderStore = (*IdentityProviderStore)(nil)

type NewIdentityProviderFunc func(idp kolide.IdentityProvider) (*kolide.IdentityProvider, error)

type SaveIdentityProviderFunc func(idb kolide.IdentityProvider) error

type IdentityProviderFunc func(id uint) (*kolide.IdentityProvider, error)

type DeleteIdentityProviderFunc func(id uint) error

type ListIdentityProvidersFunc func() ([]kolide.IdentityProvider, error)

type IdentityProviderStore struct {
	NewIdentityProviderFunc        NewIdentityProviderFunc
	NewIdentityProviderFuncInvoked bool

	SaveIdentityProviderFunc        SaveIdentityProviderFunc
	SaveIdentityProviderFuncInvoked bool

	IdentityProviderFunc        IdentityProviderFunc
	IdentityProviderFuncInvoked bool

	DeleteIdentityProviderFunc        DeleteIdentityProviderFunc
	DeleteIdentityProviderFuncInvoked bool

	ListIdentityProvidersFunc        ListIdentityProvidersFunc
	ListIdentityProvidersFuncInvoked bool
}

func (s *IdentityProviderStore) NewIdentityProvider(idp kolide.IdentityProvider) (*kolide.IdentityProvider, error) {
	s.NewIdentityProviderFuncInvoked = true
	return s.NewIdentityProviderFunc(idp)
}

func (s *IdentityProviderStore) SaveIdentityProvider(idb kolide.IdentityProvider) error {
	s.SaveIdentityProviderFuncInvoked = true
	return s.SaveIdentityProviderFunc(idb)
}

func (s *IdentityProviderStore) IdentityProvider(id uint) (*kolide.IdentityProvider, error) {
	s.IdentityProviderFuncInvoked = true
	return s.IdentityProviderFunc(id)
}

func (s *IdentityProviderStore) DeleteIdentityProvider(id uint) error {
	s.DeleteIdentityProviderFuncInvoked = true
	return s.DeleteIdentityProviderFunc(id)
}

func (s *IdentityProviderStore) ListIdentityProviders() ([]kolide.IdentityProvider, error) {
	s.ListIdentityProvidersFuncInvoked = true
	return s.ListIdentityProvidersFunc()
}
