variable "prefix" {}
variable "dynamodb_table" {}
variable "vpc" {}
variable "remote_state" {}
variable "mysql_secret" {}
variable "eks_cluster" {}
variable "redis_cluster" {}
variable "base_domain" {}
variable "ecs_cluster" {}
variable "kms_key" {}
variable "installer_bucket" {}
variable "oidc_provider_arn" {}
variable "oidc_provider" {}
variable "ecr" {}
variable "license_key" {}
variable "apm_url" {}
variable "apm_token" {}
