package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"slices"
	"strings"

	maintained_apps "github.com/fleetdm/fleet/v4/ee/maintained-apps"
)

// targetApp is one (slug, version) entry selected for verification.
type targetApp struct {
	Slug string
	Name string
	// ManifestPath is the output manifest path relative to the repo root.
	ManifestPath string
	Manifest     *maintained_apps.FMAManifestApp
	// IsNew is true when the manifest does not exist at the base ref.
	IsNew bool
	// ChangedFields lists which installer-relevant fields changed vs. the
	// base ref (version, installer_url, sha256).
	ChangedFields []string
}

// changedApps returns the apps whose installer-relevant manifest fields
// (version, installer_url, sha256) changed between cfg.changedFrom and the
// working tree, including new, still-uncommitted manifests (the ingest
// workflow runs this tool before committing).
func changedApps(ctx context.Context, cfg *config) ([]targetApp, error) {
	paths := make(map[string]struct{})

	// -z (NUL-separated) so paths with characters git would otherwise
	// C-quote parse exactly.
	diffOut, err := gitOutput(ctx, cfg.repoRoot, "diff", "--name-only", "-z", cfg.changedFrom, "--", maintained_apps.OutputPath)
	if err != nil {
		return nil, fmt.Errorf("git diff against %s: %w", cfg.changedFrom, err)
	}
	for p := range strings.SplitSeq(diffOut, "\x00") {
		if p != "" {
			paths[p] = struct{}{}
		}
	}

	// New manifests generated by the ingester are untracked until the PR
	// commit is created, so git diff alone misses them.
	untrackedOut, err := gitOutput(ctx, cfg.repoRoot, "ls-files", "--others", "--exclude-standard", "-z", "--", maintained_apps.OutputPath)
	if err != nil {
		return nil, fmt.Errorf("git ls-files: %w", err)
	}
	for p := range strings.SplitSeq(untrackedOut, "\x00") {
		if p != "" {
			paths[p] = struct{}{}
		}
	}

	names, err := appNamesBySlug(cfg.repoRoot)
	if err != nil {
		return nil, err
	}

	var targets []targetApp
	for manifestPath := range paths {
		slug, ok := slugFromManifestPath(manifestPath)
		if !ok {
			continue
		}

		current, err := manifestAppFromFile(filepath.Join(cfg.repoRoot, filepath.FromSlash(manifestPath)))
		if err != nil {
			if os.IsNotExist(err) {
				// Manifest deleted (app removed from the catalog); nothing to verify.
				continue
			}
			return nil, fmt.Errorf("parsing manifest %s: %w", manifestPath, err)
		}
		current.Slug = slug

		target := targetApp{
			Slug:         slug,
			Name:         names[slug],
			ManifestPath: manifestPath,
			Manifest:     current,
		}
		if target.Name == "" {
			target.Name = current.SlugAppName()
		}

		baseOut, err := gitOutput(ctx, cfg.repoRoot, "show", cfg.changedFrom+":"+manifestPath)
		if err != nil {
			// The manifest doesn't exist at the base ref: new app.
			target.IsNew = true
			target.ChangedFields = []string{"new"}
			targets = append(targets, target)
			continue
		}
		base, err := manifestAppFromBytes([]byte(baseOut))
		if err != nil {
			return nil, fmt.Errorf("parsing base manifest %s@%s: %w", manifestPath, cfg.changedFrom, err)
		}

		if base.Version != current.Version {
			target.ChangedFields = append(target.ChangedFields, "version")
		}
		if base.InstallerURL != current.InstallerURL {
			target.ChangedFields = append(target.ChangedFields, "installer_url")
		}
		if base.SHA256 != current.SHA256 {
			target.ChangedFields = append(target.ChangedFields, "sha256")
		}
		if len(target.ChangedFields) == 0 {
			// Script-only or query-only change; the installer is unchanged, so
			// there is nothing new to verify.
			continue
		}
		targets = append(targets, target)
	}

	sortTargets(targets)
	return targets, nil
}

// allApps returns every app in the catalog (used by --all, e.g. the pin
// backfill).
func allApps(cfg *config) ([]targetApp, error) {
	names, err := appNamesBySlug(cfg.repoRoot)
	if err != nil {
		return nil, err
	}

	var targets []targetApp
	for slug, name := range names {
		manifestPath := path.Join(maintained_apps.OutputPath, slug+".json")
		manifest, err := manifestAppFromFile(filepath.Join(cfg.repoRoot, filepath.FromSlash(manifestPath)))
		if err != nil {
			return nil, fmt.Errorf("parsing manifest %s: %w", manifestPath, err)
		}
		manifest.Slug = slug
		targets = append(targets, targetApp{
			Slug:         slug,
			Name:         name,
			ManifestPath: manifestPath,
			Manifest:     manifest,
		})
	}

	sortTargets(targets)
	return targets, nil
}

func sortTargets(targets []targetApp) {
	slices.SortFunc(targets, func(a, b targetApp) int { return strings.Compare(a.Slug, b.Slug) })
}

// slugFromManifestPath maps "ee/maintained-apps/outputs/<token>/<platform>.json"
// to "<token>/<platform>"; it returns false for apps.json and anything else
// that isn't an app manifest.
func slugFromManifestPath(manifestPath string) (string, bool) {
	rel := strings.TrimPrefix(manifestPath, maintained_apps.OutputPath+"/")
	if rel == manifestPath || !strings.HasSuffix(rel, ".json") {
		return "", false
	}
	rel = strings.TrimSuffix(rel, ".json")
	parts := strings.Split(rel, "/")
	if len(parts) != 2 {
		return "", false
	}
	if parts[1] != "darwin" && parts[1] != "windows" {
		return "", false
	}
	return rel, true
}

func appNamesBySlug(repoRoot string) (map[string]string, error) {
	listBytes, err := os.ReadFile(filepath.Join(repoRoot, filepath.FromSlash(maintained_apps.OutputPath), "apps.json"))
	if err != nil {
		return nil, fmt.Errorf("reading apps list file: %w", err)
	}
	var list maintained_apps.FMAListFile
	if err := json.Unmarshal(listBytes, &list); err != nil {
		return nil, fmt.Errorf("unmarshaling apps list file: %w", err)
	}
	names := make(map[string]string, len(list.Apps))
	for _, a := range list.Apps {
		names[a.Slug] = a.Name
	}
	return names, nil
}

func manifestAppFromFile(filePath string) (*maintained_apps.FMAManifestApp, error) {
	fileBytes, err := os.ReadFile(filePath)
	if err != nil {
		return nil, err
	}
	return manifestAppFromBytes(fileBytes)
}

func manifestAppFromBytes(fileBytes []byte) (*maintained_apps.FMAManifestApp, error) {
	var manifest maintained_apps.FMAManifestFile
	if err := json.Unmarshal(fileBytes, &manifest); err != nil {
		return nil, err
	}
	if len(manifest.Versions) == 0 {
		return nil, errors.New("manifest has no versions")
	}
	return manifest.Versions[0], nil
}

func gitOutput(ctx context.Context, repoRoot string, args ...string) (string, error) {
	fullArgs := append([]string{"-C", repoRoot}, args...)
	out, err := exec.CommandContext(ctx, "git", fullArgs...).Output()
	if err != nil {
		return "", err
	}
	return string(out), nil
}
