/**
 * MicrosoftComplianceTenant.js
 *
 * @description :: A model definition represents a database table/collection.
 * @docs        :: https://sailsjs.com/docs/concepts/models-and-orm/models
 */

module.exports = {

  attributes: {

    //  ╔═╗╦═╗╦╔╦╗╦╔╦╗╦╦  ╦╔═╗╔═╗
    //  ╠═╝╠╦╝║║║║║ ║ ║╚╗╔╝║╣ ╚═╗
    //  ╩  ╩╚═╩╩ ╩╩ ╩ ╩ ╚╝ ╚═╝╚═╝

    fleetServerSecret: {
      type: 'string',
      description: 'The randomly generated API token generated by the Fleet website for the Fleet server used to authenticate requests coming from this compliance tenant.'
    },

    entraTenantId: {
      type: 'string',
      description: 'The Microsoft entra tenant ID for this compliance tenant',
      unique: true,
      required: true,
    },

    fleetInstanceUrl: {
      type: 'string',
      description: 'The url of the connected Fleet instance.',
      unique: true,
      required: true,
    },

    setupCompleted: {
      type: 'boolean',
      defaultsTo: false,
      description: 'Whether or not the Fleet Compliance partner application has been provisioned on the tenant, created a policy, and assigned the created policy to all users.',
    },

    lastHeartbeatAt: {
      type: 'string',
      description: 'A JS timestamp (Epoch MS) representing the last time a heartbeat was sent for this compliance tenant'
    },

    adminConsented: {
      type: 'boolean',
      description: 'Whether or not an Intune admin consented to add Fleet as a compliance partner.',
      extendedDescription: 'Used only during the initial setup.',
    },

    stateTokenForAdminConsent: {
      type: 'string',
      description: 'A token used to authenticate admin consent webhook requests.',
    },

    setupError: {
      type: 'string',
      description: 'The last error logged from a Microsoft API during the initial setup of the complaince tenant (If there were any)',
    }

    //  ╔═╗╔╦╗╔╗ ╔═╗╔╦╗╔═╗
    //  ║╣ ║║║╠╩╗║╣  ║║╚═╗
    //  ╚═╝╩ ╩╚═╝╚═╝═╩╝╚═╝


    //  ╔═╗╔═╗╔═╗╔═╗╔═╗╦╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
    //  ╠═╣╚═╗╚═╗║ ║║  ║╠═╣ ║ ║║ ║║║║╚═╗
    //  ╩ ╩╚═╝╚═╝╚═╝╚═╝╩╩ ╩ ╩ ╩╚═╝╝╚╝╚═╝

  },

};

