// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AssetFile is one file the exporter wrote.
 */
export class AssetFile {
    "name": string;
    "path": string;
    "size": number;
    "mod_time_ms": number;

    /** Creates a new AssetFile instance. */
    constructor($$source: Partial<AssetFile> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("mod_time_ms" in $$source)) {
            this["mod_time_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetFile instance from a string or object.
     */
    static createFrom($$source: any = {}): AssetFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetFile($$parsedSource as Partial<AssetFile>);
    }
}

/**
 * Config is one saved MDM-assets export configuration.
 */
export class Config {
    "id": string;
    "name": string;

    /**
     * MySQL connection — defaults mirror the tool's consts (fleet / insecure /
     * localhost:3306 / fleet).
     */
    "db_user": string;
    "db_password": string;
    "db_address": string;
    "db_name": string;

    /**
     * Key is the server private key used to decrypt the assets (export's -key,
     * required).
     */
    "key": string;

    /**
     * Dir is the export output directory; empty means the Fleet repo root.
     */
    "dir": string;

    /**
     * AssetName optionally limits the export to a single asset (export's -name);
     * empty exports the full set.
     */
    "asset_name": string;
    "created_at_ms": number;
    "updated_at_ms": number;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("db_user" in $$source)) {
            this["db_user"] = "";
        }
        if (!("db_password" in $$source)) {
            this["db_password"] = "";
        }
        if (!("db_address" in $$source)) {
            this["db_address"] = "";
        }
        if (!("db_name" in $$source)) {
            this["db_name"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }
        if (!("asset_name" in $$source)) {
            this["asset_name"] = "";
        }
        if (!("created_at_ms" in $$source)) {
            this["created_at_ms"] = 0;
        }
        if (!("updated_at_ms" in $$source)) {
            this["updated_at_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * ExportResult is a finished export run: captured output plus the files it
 * produced. ExitCode is nil if the process was killed/timed out.
 */
export class ExportResult {
    "exit_code": number | null;
    "stdout": string;
    "stderr": string;
    "files": AssetFile[];

    /** Creates a new ExportResult instance. */
    constructor($$source: Partial<ExportResult> = {}) {
        if (!("exit_code" in $$source)) {
            this["exit_code"] = null;
        }
        if (!("stdout" in $$source)) {
            this["stdout"] = "";
        }
        if (!("stderr" in $$source)) {
            this["stderr"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportResult {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField3_0($$parsedSource["files"]);
        }
        return new ExportResult($$parsedSource as Partial<ExportResult>);
    }
}

// Private type creation functions
const $$createType0 = AssetFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
