const TEST_GOOD_PASSWORD = "password123#";
const BAD_PASSWORD_LENGTH = "password12#";
const BAD_PASSWORD_NO_NUMBER = "password####";
const BAD_PASSWORD_NO_SYMBOL = "password1234";

export default {
  TEST_GOOD_PASSWORD,
  BAD_PASSWORD_LENGTH,
  BAD_PASSWORD_NO_NUMBER,
  BAD_PASSWORD_NO_SYMBOL,
};
