{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mysql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.auth.rootPassword | default (randAlphaNum 16) | quote }}
  mysql-password: {{ .Values.auth.password | default (randAlphaNum 16) | quote }}
{{- end }}
