{{- if not .Values.auth.existingSecret }}
{{- $secretName := include "mysql.fullname" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $existingRootPassword := "" }}
{{- $existingPassword := "" }}
{{- if $existingSecret }}
{{- $existingRootPassword = (index $existingSecret.data "mysql-root-password" | b64dec) }}
{{- $existingPassword = (index $existingSecret.data "mysql-password" | b64dec) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mysql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.auth.rootPassword | default $existingRootPassword | default (randAlphaNum 16) | quote }}
  mysql-password: {{ .Values.auth.password | default $existingPassword | default (randAlphaNum 16) | quote }}
{{- end }}
