// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FleetctlService exposes fleetctl binary resolution, config read/write, and
 * a capture runner. Mirrors fleetctl.rs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as fleetctl$0 from "../internal/fleetctl/models.js";

export function FleetctlReadConfigRaw(): $CancellablePromise<fleetctl$0.RawConfig> {
    return $Call.ByID(2854721858).then(($result: any) => {
        return $$createType0($result);
    });
}

export function FleetctlReadContext(): $CancellablePromise<fleetctl$0.ContextInfo> {
    return $Call.ByID(645988397).then(($result: any) => {
        return $$createType1($result);
    });
}

export function FleetctlResolveBinary(repo: string, settingsPath: string): $CancellablePromise<fleetctl$0.ResolvedBinary> {
    return $Call.ByID(3052841771, repo, settingsPath).then(($result: any) => {
        return $$createType2($result);
    });
}

export function FleetctlRunCapture(program: string, cwd: string, args: string[], env: { [_ in string]?: string }, stdinData: string, timeoutMS: number): $CancellablePromise<fleetctl$0.CapturedRun> {
    return $Call.ByID(1009820515, program, cwd, args, env, stdinData, timeoutMS).then(($result: any) => {
        return $$createType3($result);
    });
}

export function FleetctlSaveConfig(yaml: string): $CancellablePromise<void> {
    return $Call.ByID(2856455237, yaml);
}

// Private type creation functions
const $$createType0 = fleetctl$0.RawConfig.createFrom;
const $$createType1 = fleetctl$0.ContextInfo.createFrom;
const $$createType2 = fleetctl$0.ResolvedBinary.createFrom;
const $$createType3 = fleetctl$0.CapturedRun.createFrom;
