// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService exposes branch listing, status, and checkout. Mirrors git.rs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gitrepo$0 from "../internal/gitrepo/models.js";

export function GitAddWorktree(repo: string, path: string, ref: string): $CancellablePromise<string> {
    return $Call.ByID(4094837978, repo, path, ref);
}

export function GitBranchStatus(repo: string): $CancellablePromise<gitrepo$0.BranchStatus> {
    return $Call.ByID(3298050234, repo).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GitCheckout(repo: string, branch: string): $CancellablePromise<string> {
    return $Call.ByID(1149198612, repo, branch);
}

export function GitDiscardAndCheckout(repo: string, branch: string): $CancellablePromise<string> {
    return $Call.ByID(648024095, repo, branch);
}

export function GitFetch(repo: string): $CancellablePromise<string> {
    return $Call.ByID(3814920816, repo);
}

export function GitListBranches(repo: string, filter: string, query: string, limit: number | null): $CancellablePromise<gitrepo$0.Branch[]> {
    return $Call.ByID(1343702948, repo, filter, query, limit).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Worktree management — used by multi-server to build/run different branches
 * in parallel from one clone.
 */
export function GitListWorktrees(repo: string): $CancellablePromise<gitrepo$0.Worktree[]> {
    return $Call.ByID(2234859834, repo).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GitPull(repo: string): $CancellablePromise<string> {
    return $Call.ByID(650648391, repo);
}

export function GitRemoveWorktree(repo: string, path: string, force: boolean): $CancellablePromise<string> {
    return $Call.ByID(4143669837, repo, path, force);
}

export function GitStashAndCheckout(repo: string, branch: string): $CancellablePromise<string> {
    return $Call.ByID(1531621606, repo, branch);
}

// Private type creation functions
const $$createType0 = gitrepo$0.BranchStatus.createFrom;
const $$createType1 = gitrepo$0.Branch.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = gitrepo$0.Worktree.createFrom;
const $$createType4 = $Create.Array($$createType3);
