// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MdmAssetsService runs the in-repo tools/mdm/assets exporter and persists saved
 * export configs. A separate top-level tab drives it; it's independent of the
 * active Fleet server (the export targets whatever MySQL the config points at).
 * Thin adapter over internal/mdmassets.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mdmassets$0 from "../internal/mdmassets/models.js";

/**
 * MdmAssetsConfigDelete removes a config by id.
 */
export function MdmAssetsConfigDelete(id: string): $CancellablePromise<void> {
    return $Call.ByID(346739743, id);
}

/**
 * MdmAssetsConfigSave upserts a config (backend-stamped timestamps).
 */
export function MdmAssetsConfigSave(cfg: mdmassets$0.Config): $CancellablePromise<mdmassets$0.Config> {
    return $Call.ByID(3201112753, cfg).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * MdmAssetsConfigsList returns all saved export configs.
 */
export function MdmAssetsConfigsList(): $CancellablePromise<mdmassets$0.Config[]> {
    return $Call.ByID(2648758753).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * MdmAssetsDefaultDir is the default export destination (the primary repo root),
 * or "" if server 1 has no repo configured yet.
 */
export function MdmAssetsDefaultDir(): $CancellablePromise<string> {
    return $Call.ByID(1611715110);
}

/**
 * MdmAssetsExport runs the exporter for a config and returns the captured
 * output plus the files written.
 */
export function MdmAssetsExport(cfg: mdmassets$0.Config): $CancellablePromise<mdmassets$0.ExportResult> {
    return $Call.ByID(2974703928, cfg).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * MdmAssetsReadFile returns a file's contents (for the per-file copy button).
 */
export function MdmAssetsReadFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(3414110948, path);
}

// Private type creation functions
const $$createType0 = mdmassets$0.Config.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = mdmassets$0.ExportResult.createFrom;
