// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PerfService exposes the osquery-perf template catalog. Mirrors perf.rs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as perf$0 from "../internal/perf/models.js";

export function PerfListTemplates(): $CancellablePromise<perf$0.Template[]> {
    return $Call.ByID(1854920521).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = perf$0.Template.createFrom;
const $$createType1 = $Create.Array($$createType0);
