// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScepService runs local SCEP servers (one shared in-repo binary, many
 * depot-based profiles) for QA. A separate top-level tab drives it; it's
 * independent of the active Fleet server. Thin adapter over internal/scep.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scep$0 from "../internal/scep/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../internal/settings/models.js";

/**
 * BinaryStatus reports the cached scepserver binary's presence + build time
 * without building it.
 */
export function BinaryStatus(): $CancellablePromise<scep$0.BinaryInfo> {
    return $Call.ByID(2470752418).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DepotInfo reads a depot's CA identity (thumbprint / issuer DN) from an
 * explicit path.
 */
export function DepotInfo(depotPath: string): $CancellablePromise<scep$0.DepotInfo> {
    return $Call.ByID(756013097, depotPath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * EnsureBinary returns the cached binary, building it from the primary repo
 * (server 1) on first use.
 */
export function EnsureBinary(): $CancellablePromise<scep$0.BinaryInfo> {
    return $Call.ByID(3865653774).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * InitCA creates a new CA in depotPath. Fails clearly if a CA already exists.
 */
export function InitCA(depotPath: string, params: scep$0.InitCAParams): $CancellablePromise<scep$0.DepotInfo> {
    return $Call.ByID(2478273599, depotPath, params).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * LanIP returns the host's primary LAN IPv4 for building SCEP URLs.
 */
export function LanIP(): $CancellablePromise<string> {
    return $Call.ByID(3752712981);
}

/**
 * ProfileDepotInfo reads a profile's resolved depot CA identity in one call.
 */
export function ProfileDepotInfo(p: settings$0.ScepProfile): $CancellablePromise<scep$0.DepotInfo> {
    return $Call.ByID(2235580624, p).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RebuildBinary force-rebuilds the cached binary from the primary repo (e.g.
 * after pulling new code).
 */
export function RebuildBinary(): $CancellablePromise<scep$0.BinaryInfo> {
    return $Call.ByID(395662193).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResolveDepot returns the profile's depot directory (its explicit path, or the
 * managed default under the depots dir).
 */
export function ResolveDepot(p: settings$0.ScepProfile): $CancellablePromise<string> {
    return $Call.ByID(574501327, p);
}

/**
 * StartProfile launches a profile's SCEP server: ensures the binary, resolves
 * the depot (which must have a CA), and starts the process with logs streamed
 * to the profile's channel. Concurrent — one process per profile.
 */
export function StartProfile(p: settings$0.ScepProfile): $CancellablePromise<void> {
    return $Call.ByID(1100047084, p);
}

/**
 * StopProfile stops a profile's running SCEP server.
 */
export function StopProfile(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(4294835106, profileID);
}

// Private type creation functions
const $$createType0 = scep$0.BinaryInfo.createFrom;
const $$createType1 = scep$0.DepotInfo.createFrom;
