// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TroubleshootService exposes port/pattern process scans and kill. Mirrors
 * troubleshoot.rs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as troubleshoot$0 from "../internal/troubleshoot/models.js";

export function TroubleshootKillPid(pid: number): $CancellablePromise<troubleshoot$0.KillOutcome> {
    return $Call.ByID(1692691043, pid).then(($result: any) => {
        return $$createType0($result);
    });
}

export function TroubleshootScanPattern(pattern: string): $CancellablePromise<troubleshoot$0.DetectedProcess[]> {
    return $Call.ByID(2260013595, pattern).then(($result: any) => {
        return $$createType2($result);
    });
}

export function TroubleshootScanPort(port: number): $CancellablePromise<troubleshoot$0.DetectedProcess[]> {
    return $Call.ByID(2265783308, port).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = troubleshoot$0.KillOutcome.createFrom;
const $$createType1 = troubleshoot$0.DetectedProcess.createFrom;
const $$createType2 = $Create.Array($$createType1);
