// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TufService drives a local TUF test repo + fleetd installer generation by
 * running tools/tuf/test/main.sh (via the process engine, so its output streams
 * to the Logs ring), and offers server-status / kill / delete-assets helpers.
 * A separate top-level tab drives it; it's independent of the active server.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../internal/settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as troubleshoot$0 from "../internal/troubleshoot/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tuf$0 from "../internal/tuf/models.js";

/**
 * TufAssetsExist reports whether a generated TUF repo is present (so the UI can
 * only offer "Delete assets" when there's something to delete).
 */
export function TufAssetsExist(): $CancellablePromise<boolean> {
    return $Call.ByID(3431525854);
}

/**
 * TufDeleteAssets removes the generated TUF repo (<repo>/test_tuf).
 */
export function TufDeleteAssets(): $CancellablePromise<void> {
    return $Call.ByID(312501096);
}

/**
 * TufKillServer stops Hangar's managed file-server and reaps any other process
 * bound to the TUF port (e.g. an orphan from a prior run or the CLI).
 */
export function TufKillServer(): $CancellablePromise<troubleshoot$0.KillOutcome[]> {
    return $Call.ByID(2146765721).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * TufServerStatus reports whether the local TUF server answers on :8081.
 */
export function TufServerStatus(): $CancellablePromise<tuf$0.ServerStatus> {
    return $Call.ByID(1649989895).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * TufStartBuild runs main.sh with the config's env from the primary repo. The
 * run streams to the tuf-build log channel; when it exits the TUF file-server it
 * spawned keeps serving (status flips up).
 */
export function TufStartBuild(cfg: settings$0.TufConfig): $CancellablePromise<void> {
    return $Call.ByID(2030310602, cfg);
}

/**
 * TufStartServer runs the TUF file-server for the manual "Start server" button.
 * Requires a built repo (the build starts the server itself).
 */
export function TufStartServer(): $CancellablePromise<void> {
    return $Call.ByID(1873516069);
}

/**
 * TufStopBuild cancels a running build.
 */
export function TufStopBuild(): $CancellablePromise<void> {
    return $Call.ByID(1829058698);
}

// Private type creation functions
const $$createType0 = troubleshoot$0.KillOutcome.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = tuf$0.ServerStatus.createFrom;
