// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DetectedProcess is a process found by a scan.
 */
export class DetectedProcess {
    "pid": number;
    "command": string;

    /** Creates a new DetectedProcess instance. */
    constructor($$source: Partial<DetectedProcess> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetectedProcess instance from a string or object.
     */
    static createFrom($$source: any = {}): DetectedProcess {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DetectedProcess($$parsedSource as Partial<DetectedProcess>);
    }
}

/**
 * KillOutcome reports the result of terminating a pid.
 */
export class KillOutcome {
    "pid": number;
    "gone": boolean;
    "used_kill": boolean;
    "error": string | null;

    /** Creates a new KillOutcome instance. */
    constructor($$source: Partial<KillOutcome> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("gone" in $$source)) {
            this["gone"] = false;
        }
        if (!("used_kill" in $$source)) {
            this["used_kill"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KillOutcome instance from a string or object.
     */
    static createFrom($$source: any = {}): KillOutcome {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KillOutcome($$parsedSource as Partial<KillOutcome>);
    }
}
