services:
  pmm-server:
    image: percona/pmm-server:2
    container_name: pmm-server
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - pmm-server-data:/srv
    restart: unless-stopped

  pmm-client:
    image: percona/pmm-client:2
    container_name: pmm-client
    depends_on:
      - pmm-server
    networks:
      - default
      - fleet_default
    environment:
      PMM_AGENT_SERVER_ADDRESS: pmm-server:443
      PMM_AGENT_SERVER_INSECURE_TLS: "1"
      PMM_AGENT_SERVER_USERNAME: admin
      PMM_AGENT_SERVER_PASSWORD: admin
      PMM_AGENT_SETUP: "1"
      PMM_AGENT_CONFIG_FILE: /usr/local/percona/pmm2/pmm-agent.yaml
    volumes:
      - pmm-client-data:/usr/local/percona/pmm2
    restart: unless-stopped

volumes:
  pmm-server-data:
  pmm-client-data:

networks:
  fleet_default:
    external: true
