package luks

import (
	"errors"
	"regexp"

	"github.com/fleetdm/fleet/v4/orbit/pkg/dialog"
)

type LuksDump struct {
	Keyslots map[string]Keyslot `json:"keyslots"` // keyslot -> salt
	Tokens   map[string]Token   `json:"tokens"`
}

type Keyslot struct {
	KDF KDF `json:"kdf"`
}

type KDF struct {
	Salt string `json:"salt"`
}

// Token represents an entry from the LUKS2 "tokens" object. We only need the
// type field to identify TPM2/FIDO2/recovery setups; other fields are ignored.
type Token struct {
	Type string `json:"type"`
}

// EncryptionType values returned by DetectEncryptionType. These are local to
// orbit — the server does not currently persist or care about which one the
// host is on; the value is only used to branch dialog copy when prompting the
// end user during escrow.
const (
	EncryptionTypePassphrase = "passphrase"
	EncryptionTypeTPM2       = "tpm2"
	EncryptionTypeFIDO2      = "fido2"
	EncryptionTypeRecovery   = "recovery"
)

// LUKS2 token type identifiers emitted by systemd-cryptenroll.
const (
	tokenTypeSystemdTPM2     = "systemd-tpm2"
	tokenTypeSystemdFIDO2    = "systemd-fido2"
	tokenTypeSystemdRecovery = "systemd-recovery"
)

// DetectEncryptionType inspects a LUKS2 dump's tokens and returns the
// best-matching encryption type for the volume. Priority order when multiple
// tokens are present is tpm2 > fido2 > recovery > passphrase. A nil dump, an
// empty tokens map, or unrecognized token types all map to
// EncryptionTypePassphrase.
func DetectEncryptionType(dump *LuksDump) string {
	if dump == nil {
		return EncryptionTypePassphrase
	}

	var hasFIDO2, hasRecovery bool
	for _, tok := range dump.Tokens {
		switch tok.Type {
		case tokenTypeSystemdTPM2:
			return EncryptionTypeTPM2
		case tokenTypeSystemdFIDO2:
			hasFIDO2 = true
		case tokenTypeSystemdRecovery:
			hasRecovery = true
		}
	}

	switch {
	case hasFIDO2:
		return EncryptionTypeFIDO2
	case hasRecovery:
		return EncryptionTypeRecovery
	}
	return EncryptionTypePassphrase
}

type KeyEscrower interface {
	SendLinuxKeyEscrowResponse(LuksResponse) error
}

type LuksRunner struct {
	escrower KeyEscrower
	notifier dialog.Dialog //nolint:structcheck,unused
}

type LuksResponse struct {
	// Passphrase is a newly created passphrase generated by fleetd for securing the LUKS volume.
	// This passphrase will be securely escrowed to the server.
	Passphrase string

	// KeySlot specifies the LUKS key slot where this new passphrase was created.
	// It is currently not used, but may be useful in the future for passphrase rotation.
	KeySlot *uint

	// Salt is the salt used to generate the LUKS key.
	Salt string

	// Err is the error message that occurred during the escrow process.
	Err string
}

func New(escrower KeyEscrower) *LuksRunner {
	return &LuksRunner{
		escrower: escrower,
	}
}

func extractJSON(input []byte) ([]byte, error) {
	// Regular expression to extract JSON
	re := regexp.MustCompile(`(?s)\{.*\}`)
	match := re.FindString(string(input))
	if match == "" {
		return nil, errors.New("no JSON found")
	}
	return []byte(match), nil
}
