// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CapturedRun is the result of a one-shot command.
 */
export class CapturedRun {
    "exit_code": number | null;
    "stdout": string;
    "stderr": string;

    /** Creates a new CapturedRun instance. */
    constructor($$source: Partial<CapturedRun> = {}) {
        if (!("exit_code" in $$source)) {
            this["exit_code"] = null;
        }
        if (!("stdout" in $$source)) {
            this["stdout"] = "";
        }
        if (!("stderr" in $$source)) {
            this["stderr"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CapturedRun instance from a string or object.
     */
    static createFrom($$source: any = {}): CapturedRun {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CapturedRun($$parsedSource as Partial<CapturedRun>);
    }
}

/**
 * ContextInfo describes the parsed fleetctl config.
 */
export class ContextInfo {
    "config_path": string;
    "exists": boolean;
    "current": ContextSummary | null;
    "contexts": ContextSummary[];

    /** Creates a new ContextInfo instance. */
    constructor($$source: Partial<ContextInfo> = {}) {
        if (!("config_path" in $$source)) {
            this["config_path"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("current" in $$source)) {
            this["current"] = null;
        }
        if (!("contexts" in $$source)) {
            this["contexts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ContextInfo {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("current" in $$parsedSource) {
            $$parsedSource["current"] = $$createField2_0($$parsedSource["current"]);
        }
        if ("contexts" in $$parsedSource) {
            $$parsedSource["contexts"] = $$createField3_0($$parsedSource["contexts"]);
        }
        return new ContextInfo($$parsedSource as Partial<ContextInfo>);
    }
}

/**
 * ContextSummary is one fleetctl context (sensitive token reduced to a bool).
 */
export class ContextSummary {
    "name": string;
    "address": string | null;
    "email": string | null;
    "has_token": boolean;

    /** Creates a new ContextSummary instance. */
    constructor($$source: Partial<ContextSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = null;
        }
        if (!("email" in $$source)) {
            this["email"] = null;
        }
        if (!("has_token" in $$source)) {
            this["has_token"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ContextSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContextSummary($$parsedSource as Partial<ContextSummary>);
    }
}

/**
 * RawConfig is the raw fleetctl config file contents.
 */
export class RawConfig {
    "path": string;
    "exists": boolean;
    "contents": string;

    /** Creates a new RawConfig instance. */
    constructor($$source: Partial<RawConfig> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("contents" in $$source)) {
            this["contents"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RawConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): RawConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RawConfig($$parsedSource as Partial<RawConfig>);
    }
}

/**
 * ResolvedBinary reports where fleetctl was found and how.
 */
export class ResolvedBinary {
    "path": string;

    /**
     * "settings" | "build" | "missing"
     */
    "source": string;
    "exists": boolean;

    /** Creates a new ResolvedBinary instance. */
    constructor($$source: Partial<ResolvedBinary> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolvedBinary instance from a string or object.
     */
    static createFrom($$source: any = {}): ResolvedBinary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResolvedBinary($$parsedSource as Partial<ResolvedBinary>);
    }
}

// Private type creation functions
const $$createType0 = ContextSummary.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
