// Automatically generated by mockimpl. DO NOT EDIT!

package mock

import (
	"context"
	"sync"

	"github.com/fleetdm/fleet/v4/server/mdm/android"
	"github.com/fleetdm/fleet/v4/server/mdm/android/service/androidmgmt"
	"google.golang.org/api/androidmanagement/v1"
)

var _ androidmgmt.Client = (*Client)(nil)

type SignupURLsCreateFunc func(ctx context.Context, serverURL string, callbackURL string) (*android.SignupDetails, error)

type EnterprisesCreateFunc func(ctx context.Context, req androidmgmt.EnterprisesCreateRequest) (androidmgmt.EnterprisesCreateResponse, error)

type EnterprisesPoliciesPatchFunc func(ctx context.Context, policyName string, policy *androidmanagement.Policy) error

type EnterprisesEnrollmentTokensCreateFunc func(ctx context.Context, enterpriseName string, token *androidmanagement.EnrollmentToken) (*androidmanagement.EnrollmentToken, error)

type EnterpriseDeleteFunc func(ctx context.Context, enterpriseName string) error

type EnterpriseGetFunc func(ctx context.Context, enterpriseName string) (*androidmanagement.Enterprise, error)

type EnterprisesListFunc func(ctx context.Context) ([]*androidmanagement.Enterprise, error)

type SetAuthenticationSecretFunc func(secret string) error

type Client struct {
	SignupURLsCreateFunc        SignupURLsCreateFunc
	SignupURLsCreateFuncInvoked bool

	EnterprisesCreateFunc        EnterprisesCreateFunc
	EnterprisesCreateFuncInvoked bool

	EnterprisesPoliciesPatchFunc        EnterprisesPoliciesPatchFunc
	EnterprisesPoliciesPatchFuncInvoked bool

	EnterprisesEnrollmentTokensCreateFunc        EnterprisesEnrollmentTokensCreateFunc
	EnterprisesEnrollmentTokensCreateFuncInvoked bool

	EnterpriseDeleteFunc        EnterpriseDeleteFunc
	EnterpriseDeleteFuncInvoked bool

	EnterpriseGetFunc        EnterpriseGetFunc
	EnterpriseGetFuncInvoked bool

	EnterprisesListFunc        EnterprisesListFunc
	EnterprisesListFuncInvoked bool

	SetAuthenticationSecretFunc        SetAuthenticationSecretFunc
	SetAuthenticationSecretFuncInvoked bool

	mu sync.Mutex
}

func (p *Client) SignupURLsCreate(ctx context.Context, serverURL string, callbackURL string) (*android.SignupDetails, error) {
	p.mu.Lock()
	p.SignupURLsCreateFuncInvoked = true
	p.mu.Unlock()
	return p.SignupURLsCreateFunc(ctx, serverURL, callbackURL)
}

func (p *Client) EnterprisesCreate(ctx context.Context, req androidmgmt.EnterprisesCreateRequest) (androidmgmt.EnterprisesCreateResponse, error) {
	p.mu.Lock()
	p.EnterprisesCreateFuncInvoked = true
	p.mu.Unlock()
	return p.EnterprisesCreateFunc(ctx, req)
}

func (p *Client) EnterprisesPoliciesPatch(ctx context.Context, policyName string, policy *androidmanagement.Policy) error {
	p.mu.Lock()
	p.EnterprisesPoliciesPatchFuncInvoked = true
	p.mu.Unlock()
	return p.EnterprisesPoliciesPatchFunc(ctx, policyName, policy)
}

func (p *Client) EnterprisesEnrollmentTokensCreate(ctx context.Context, enterpriseName string, token *androidmanagement.EnrollmentToken) (*androidmanagement.EnrollmentToken, error) {
	p.mu.Lock()
	p.EnterprisesEnrollmentTokensCreateFuncInvoked = true
	p.mu.Unlock()
	return p.EnterprisesEnrollmentTokensCreateFunc(ctx, enterpriseName, token)
}

func (p *Client) EnterpriseDelete(ctx context.Context, enterpriseName string) error {
	p.mu.Lock()
	p.EnterpriseDeleteFuncInvoked = true
	p.mu.Unlock()
	return p.EnterpriseDeleteFunc(ctx, enterpriseName)
}

func (p *Client) EnterpriseGet(ctx context.Context, enterpriseName string) (*androidmanagement.Enterprise, error) {
	p.mu.Lock()
	p.EnterpriseGetFuncInvoked = true
	p.mu.Unlock()
	return p.EnterpriseGetFunc(ctx, enterpriseName)
}

func (p *Client) EnterprisesList(ctx context.Context) ([]*androidmanagement.Enterprise, error) {
	p.mu.Lock()
	p.EnterprisesListFuncInvoked = true
	p.mu.Unlock()
	return p.EnterprisesListFunc(ctx)
}

func (p *Client) SetAuthenticationSecret(secret string) error {
	p.mu.Lock()
	p.SetAuthenticationSecretFuncInvoked = true
	p.mu.Unlock()
	return p.SetAuthenticationSecretFunc(secret)
}
