// Automatically generated by mockimpl. DO NOT EDIT!

package mock

import (
	"context"
	"sync"

	"github.com/fleetdm/fleet/v4/server/mdm/android"
	"github.com/fleetdm/fleet/v4/server/mdm/android/service/androidmgmt"
	"google.golang.org/api/androidmanagement/v1"
)

var _ androidmgmt.Client = (*Client)(nil)

type SignupURLsCreateFunc func(serverURL string, callbackURL string) (*android.SignupDetails, error)

type EnterprisesCreateFunc func(ctx context.Context, req androidmgmt.EnterprisesCreateRequest) (androidmgmt.EnterprisesCreateResponse, error)

type EnterprisesPoliciesPatchFunc func(policyName string, policy *androidmanagement.Policy) error

type EnterprisesEnrollmentTokensCreateFunc func(enterpriseName string, token *androidmanagement.EnrollmentToken) (*androidmanagement.EnrollmentToken, error)

type EnterpriseDeleteFunc func(ctx context.Context, enterpriseID string) error

type SetFleetServerSecretFunc func(secret string)

type Client struct {
	SignupURLsCreateFunc        SignupURLsCreateFunc
	SignupURLsCreateFuncInvoked bool

	EnterprisesCreateFunc        EnterprisesCreateFunc
	EnterprisesCreateFuncInvoked bool

	EnterprisesPoliciesPatchFunc        EnterprisesPoliciesPatchFunc
	EnterprisesPoliciesPatchFuncInvoked bool

	EnterprisesEnrollmentTokensCreateFunc        EnterprisesEnrollmentTokensCreateFunc
	EnterprisesEnrollmentTokensCreateFuncInvoked bool

	EnterpriseDeleteFunc        EnterpriseDeleteFunc
	EnterpriseDeleteFuncInvoked bool

	SetFleetServerSecretFunc        SetFleetServerSecretFunc
	SetFleetServerSecretFuncInvoked bool

	mu sync.Mutex
}

func (p *Client) SignupURLsCreate(serverURL string, callbackURL string) (*android.SignupDetails, error) {
	p.mu.Lock()
	p.SignupURLsCreateFuncInvoked = true
	p.mu.Unlock()
	return p.SignupURLsCreateFunc(serverURL, callbackURL)
}

func (p *Client) EnterprisesCreate(ctx context.Context, req androidmgmt.EnterprisesCreateRequest) (androidmgmt.EnterprisesCreateResponse, error) {
	p.mu.Lock()
	p.EnterprisesCreateFuncInvoked = true
	p.mu.Unlock()
	return p.EnterprisesCreateFunc(ctx, req)
}

func (p *Client) EnterprisesPoliciesPatch(policyName string, policy *androidmanagement.Policy) error {
	p.mu.Lock()
	p.EnterprisesPoliciesPatchFuncInvoked = true
	p.mu.Unlock()
	return p.EnterprisesPoliciesPatchFunc(policyName, policy)
}

func (p *Client) EnterprisesEnrollmentTokensCreate(enterpriseName string, token *androidmanagement.EnrollmentToken) (*androidmanagement.EnrollmentToken, error) {
	p.mu.Lock()
	p.EnterprisesEnrollmentTokensCreateFuncInvoked = true
	p.mu.Unlock()
	return p.EnterprisesEnrollmentTokensCreateFunc(enterpriseName, token)
}

func (p *Client) EnterpriseDelete(ctx context.Context, enterpriseID string) error {
	p.mu.Lock()
	p.EnterpriseDeleteFuncInvoked = true
	p.mu.Unlock()
	return p.EnterpriseDeleteFunc(ctx, enterpriseID)
}

func (p *Client) SetFleetServerSecret(secret string) {
	p.mu.Lock()
	p.SetFleetServerSecretFuncInvoked = true
	p.mu.Unlock()
	p.SetFleetServerSecretFunc(secret)
}
