// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EnvVar is one row of the fleet serve environment editor.
 */
export class EnvVar {
    "key": string;
    "value": string;

    /**
     * Enabled is a per-row toggle. Defaults true so rows saved before this
     * field existed (and hand-added rows missing the key) stay applied.
     */
    "enabled": boolean;

    /** Creates a new EnvVar instance. */
    constructor($$source: Partial<EnvVar> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvVar instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvVar {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvVar($$parsedSource as Partial<EnvVar>);
    }
}

/**
 * FleetServeConfig holds the user-tunable bits of `fleet serve --dev`.
 */
export class FleetServeConfig {
    /**
     * ConfigPath is passed to --config; nil/empty omits the flag so serve
     * falls back to env vars / built-in defaults.
     */
    "config_path": string | null;

    /**
     * --dev_license
     */
    "premium": boolean;

    /**
     * --debug
     */
    "debug": boolean;

    /**
     * --logging_debug
     */
    "logging_debug": boolean;

    /**
     * Env is a slice (not a map) so the user's row order is preserved.
     */
    "env": EnvVar[];

    /** Creates a new FleetServeConfig instance. */
    constructor($$source: Partial<FleetServeConfig> = {}) {
        if (!("config_path" in $$source)) {
            this["config_path"] = null;
        }
        if (!("premium" in $$source)) {
            this["premium"] = false;
        }
        if (!("debug" in $$source)) {
            this["debug"] = false;
        }
        if (!("logging_debug" in $$source)) {
            this["logging_debug"] = false;
        }
        if (!("env" in $$source)) {
            this["env"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FleetServeConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): FleetServeConfig {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField4_0($$parsedSource["env"]);
        }
        return new FleetServeConfig($$parsedSource as Partial<FleetServeConfig>);
    }
}

/**
 * NgrokConfig configures the optional ngrok tunnel process.
 */
export class NgrokConfig {
    "enabled": boolean;
    "yml_path": string | null;
    "default_tunnels": string[];
    "start_all": boolean;

    /** Creates a new NgrokConfig instance. */
    constructor($$source: Partial<NgrokConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("yml_path" in $$source)) {
            this["yml_path"] = null;
        }
        if (!("default_tunnels" in $$source)) {
            this["default_tunnels"] = [];
        }
        if (!("start_all" in $$source)) {
            this["start_all"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NgrokConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): NgrokConfig {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("default_tunnels" in $$parsedSource) {
            $$parsedSource["default_tunnels"] = $$createField2_0($$parsedSource["default_tunnels"]);
        }
        return new NgrokConfig($$parsedSource as Partial<NgrokConfig>);
    }
}

/**
 * NgrokTunnel is one tunnel definition from ngrok.yml.
 */
export class NgrokTunnel {
    "name": string;
    "proto": string;
    "addr": string;

    /** Creates a new NgrokTunnel instance. */
    constructor($$source: Partial<NgrokTunnel> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("proto" in $$source)) {
            this["proto"] = "";
        }
        if (!("addr" in $$source)) {
            this["addr"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NgrokTunnel instance from a string or object.
     */
    static createFrom($$source: any = {}): NgrokTunnel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NgrokTunnel($$parsedSource as Partial<NgrokTunnel>);
    }
}

/**
 * NgrokYamlInfo summarizes an ngrok.yml for the Settings UI badge.
 */
export class NgrokYamlInfo {
    "valid": boolean;
    "error": string | null;
    "resolved_path": string;
    "has_authtoken": boolean;
    "tunnels": NgrokTunnel[];

    /** Creates a new NgrokYamlInfo instance. */
    constructor($$source: Partial<NgrokYamlInfo> = {}) {
        if (!("valid" in $$source)) {
            this["valid"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = null;
        }
        if (!("resolved_path" in $$source)) {
            this["resolved_path"] = "";
        }
        if (!("has_authtoken" in $$source)) {
            this["has_authtoken"] = false;
        }
        if (!("tunnels" in $$source)) {
            this["tunnels"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NgrokYamlInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): NgrokYamlInfo {
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tunnels" in $$parsedSource) {
            $$parsedSource["tunnels"] = $$createField4_0($$parsedSource["tunnels"]);
        }
        return new NgrokYamlInfo($$parsedSource as Partial<NgrokYamlInfo>);
    }
}

/**
 * PythonConfig configures the optional python http.server process.
 */
export class PythonConfig {
    "enabled": boolean;
    "port": number;
    "directory": string | null;

    /** Creates a new PythonConfig instance. */
    constructor($$source: Partial<PythonConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("directory" in $$source)) {
            this["directory"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PythonConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): PythonConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PythonConfig($$parsedSource as Partial<PythonConfig>);
    }
}

/**
 * RepoProbe is the result of validating a candidate Fleet clone.
 */
export class RepoProbe {
    "path": string;
    "valid": boolean;
    "reason": string | null;

    /** Creates a new RepoProbe instance. */
    constructor($$source: Partial<RepoProbe> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("valid" in $$source)) {
            this["valid"] = false;
        }
        if (!("reason" in $$source)) {
            this["reason"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoProbe instance from a string or object.
     */
    static createFrom($$source: any = {}): RepoProbe {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RepoProbe($$parsedSource as Partial<RepoProbe>);
    }
}

/**
 * ServerPorts holds the host ports one server's stack binds to. Server 1 keeps
 * the canonical dev defaults (8080/3306/6379/9000/9001) so existing scripts and
 * muscle memory keep working; additional servers use offset blocks so two
 * stacks never collide.
 */
export class ServerPorts {
    /**
     * fleet serve --server_address host port
     */
    "server": number;

    /**
     * docker mysql host port
     */
    "mysql": number;

    /**
     * docker redis host port
     */
    "redis": number;

    /**
     * docker s3 (object store) host port
     */
    "s3": number;

    /**
     * docker s3 console host port
     */
    "s3_console": number;

    /** Creates a new ServerPorts instance. */
    constructor($$source: Partial<ServerPorts> = {}) {
        if (!("server" in $$source)) {
            this["server"] = 0;
        }
        if (!("mysql" in $$source)) {
            this["mysql"] = 0;
        }
        if (!("redis" in $$source)) {
            this["redis"] = 0;
        }
        if (!("s3" in $$source)) {
            this["s3"] = 0;
        }
        if (!("s3_console" in $$source)) {
            this["s3_console"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerPorts instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerPorts {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerPorts($$parsedSource as Partial<ServerPorts>);
    }
}

/**
 * ServerProfile is one independent local Fleet server instance: its own git
 * worktree (so it can build/run a different branch), host ports, docker compose
 * project, and serve config. Multiple profiles can run in parallel.
 */
export class ServerProfile {
    /**
     * stable, e.g. "s1" (never reused/renumbered)
     */
    "id": string;

    /**
     * user-facing label, e.g. "main" / "n-1 repro"
     */
    "name": string;

    /**
     * accent key for the switcher/status: green|purple|blue
     */
    "color": string;

    /**
     * WorktreePath is the git worktree this server builds and runs from. For
     * server 1 this is typically the primary clone; others are `git worktree
     * add`-ed trees. nil until the user picks one.
     */
    "worktree_path": string | null;

    /**
     * Branch is informational (the branch the worktree was created on). The
     * live branch is read from git; checkout happens in the Git tab.
     */
    "branch": string | null;
    "ports": ServerPorts;

    /**
     * docker compose -p value
     */
    "compose_project": string;
    "fleet_serve": FleetServeConfig;
    "enabled": boolean;

    /** Creates a new ServerProfile instance. */
    constructor($$source: Partial<ServerProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("worktree_path" in $$source)) {
            this["worktree_path"] = null;
        }
        if (!("branch" in $$source)) {
            this["branch"] = null;
        }
        if (!("ports" in $$source)) {
            this["ports"] = (new ServerPorts());
        }
        if (!("compose_project" in $$source)) {
            this["compose_project"] = "";
        }
        if (!("fleet_serve" in $$source)) {
            this["fleet_serve"] = (new FleetServeConfig());
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerProfile {
        const $$createField5_0 = $$createType5;
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ports" in $$parsedSource) {
            $$parsedSource["ports"] = $$createField5_0($$parsedSource["ports"]);
        }
        if ("fleet_serve" in $$parsedSource) {
            $$parsedSource["fleet_serve"] = $$createField7_0($$parsedSource["fleet_serve"]);
        }
        return new ServerProfile($$parsedSource as Partial<ServerProfile>);
    }
}

/**
 * Settings is the full persisted configuration.
 * 
 * Servers is the multi-server source of truth. The legacy single-server fields
 * (RepoPath, FleetServe) are retained so settings written before multi-server
 * support still parse; Load() migrates them into Servers[0]. New code reads
 * from Servers / ActiveServerID, not the legacy fields.
 */
export class Settings {
    "repo_path": string | null;
    "fleetctl_path": string | null;
    "gitops_dir": string | null;
    "first_run_complete": boolean;
    "ngrok": NgrokConfig;
    "python_server": PythonConfig;
    "fleet_serve": FleetServeConfig;
    "theme": ThemePreference;
    "favorite_crons": string[];

    /**
     * Servers is nil in a pre-multi-server file; migrate() backfills it from
     * the legacy fields on Load so callers always see at least one server.
     */
    "servers": ServerProfile[];
    "active_server_id": string;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("repo_path" in $$source)) {
            this["repo_path"] = null;
        }
        if (!("fleetctl_path" in $$source)) {
            this["fleetctl_path"] = null;
        }
        if (!("gitops_dir" in $$source)) {
            this["gitops_dir"] = null;
        }
        if (!("first_run_complete" in $$source)) {
            this["first_run_complete"] = false;
        }
        if (!("ngrok" in $$source)) {
            this["ngrok"] = (new NgrokConfig());
        }
        if (!("python_server" in $$source)) {
            this["python_server"] = (new PythonConfig());
        }
        if (!("fleet_serve" in $$source)) {
            this["fleet_serve"] = (new FleetServeConfig());
        }
        if (!("theme" in $$source)) {
            this["theme"] = ThemePreference.$zero;
        }
        if (!("favorite_crons" in $$source)) {
            this["favorite_crons"] = [];
        }
        if (!("servers" in $$source)) {
            this["servers"] = [];
        }
        if (!("active_server_id" in $$source)) {
            this["active_server_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField4_0 = $$createType7;
        const $$createField5_0 = $$createType8;
        const $$createField6_0 = $$createType6;
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ngrok" in $$parsedSource) {
            $$parsedSource["ngrok"] = $$createField4_0($$parsedSource["ngrok"]);
        }
        if ("python_server" in $$parsedSource) {
            $$parsedSource["python_server"] = $$createField5_0($$parsedSource["python_server"]);
        }
        if ("fleet_serve" in $$parsedSource) {
            $$parsedSource["fleet_serve"] = $$createField6_0($$parsedSource["fleet_serve"]);
        }
        if ("favorite_crons" in $$parsedSource) {
            $$parsedSource["favorite_crons"] = $$createField8_0($$parsedSource["favorite_crons"]);
        }
        if ("servers" in $$parsedSource) {
            $$parsedSource["servers"] = $$createField9_0($$parsedSource["servers"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * ThemePreference is "system" (follow the OS), "light", or "dark".
 */
export enum ThemePreference {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemeSystem = "system",
    ThemeLight = "light",
    ThemeDark = "dark",
};

// Private type creation functions
const $$createType0 = EnvVar.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = NgrokTunnel.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ServerPorts.createFrom;
const $$createType6 = FleetServeConfig.createFrom;
const $$createType7 = NgrokConfig.createFrom;
const $$createType8 = PythonConfig.createFrom;
const $$createType9 = ServerProfile.createFrom;
const $$createType10 = $Create.Array($$createType9);
