// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BinaryInfo describes the cached scepserver binary.
 */
export class BinaryInfo {
    "path": string;
    "exists": boolean;

    /**
     * RFC3339 mtime, "" when absent
     */
    "built_at": string;

    /** Creates a new BinaryInfo instance. */
    constructor($$source: Partial<BinaryInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("built_at" in $$source)) {
            this["built_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BinaryInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BinaryInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BinaryInfo($$parsedSource as Partial<BinaryInfo>);
    }
}

/**
 * DepotInfo is a depot's CA identity, read from <depot>/ca.pem. Exists is false
 * (with Error set on a real failure) when the depot has no parseable CA yet —
 * the caller should prompt the user to Init a CA.
 */
export class DepotInfo {
    "depot_path": string;
    "exists": boolean;

    /**
     * SHA-1, uppercase hex, no separators
     */
    "thumbprint": string;
    "issuer_dn": string;
    "subject_dn": string;

    /**
     * RFC3339
     */
    "not_after": string;
    "error": string;

    /** Creates a new DepotInfo instance. */
    constructor($$source: Partial<DepotInfo> = {}) {
        if (!("depot_path" in $$source)) {
            this["depot_path"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("thumbprint" in $$source)) {
            this["thumbprint"] = "";
        }
        if (!("issuer_dn" in $$source)) {
            this["issuer_dn"] = "";
        }
        if (!("subject_dn" in $$source)) {
            this["subject_dn"] = "";
        }
        if (!("not_after" in $$source)) {
            this["not_after"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DepotInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DepotInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DepotInfo($$parsedSource as Partial<DepotInfo>);
    }
}

/**
 * InitCAParams are the DN + key inputs for `scepserver ca -init`.
 */
export class InitCAParams {
    "common_name": string;
    "organization": string;
    "organizational_unit": string;
    "country": string;
    "key_size": number;
    "years": number;
    "key_password": string;

    /** Creates a new InitCAParams instance. */
    constructor($$source: Partial<InitCAParams> = {}) {
        if (!("common_name" in $$source)) {
            this["common_name"] = "";
        }
        if (!("organization" in $$source)) {
            this["organization"] = "";
        }
        if (!("organizational_unit" in $$source)) {
            this["organizational_unit"] = "";
        }
        if (!("country" in $$source)) {
            this["country"] = "";
        }
        if (!("key_size" in $$source)) {
            this["key_size"] = 0;
        }
        if (!("years" in $$source)) {
            this["years"] = 0;
        }
        if (!("key_password" in $$source)) {
            this["key_password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InitCAParams instance from a string or object.
     */
    static createFrom($$source: any = {}): InitCAParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InitCAParams($$parsedSource as Partial<InitCAParams>);
    }
}
