// Automatically generated by mockimpl. DO NOT EDIT!

package mock

import (
	"context"
	"sync"

	"github.com/fleetdm/fleet/v4/server/fleet"
)

var _ fleet.DigiCertService = (*Service)(nil)

type VerifyProfileIDFunc func(ctx context.Context, config fleet.DigiCertIntegration) error

type GetCertificateFunc func(ctx context.Context, config fleet.DigiCertIntegration) (*fleet.DigiCertCertificate, error)

type Service struct {
	VerifyProfileIDFunc        VerifyProfileIDFunc
	VerifyProfileIDFuncInvoked bool

	GetCertificateFunc        GetCertificateFunc
	GetCertificateFuncInvoked bool

	mu sync.Mutex
}

func (s *Service) VerifyProfileID(ctx context.Context, config fleet.DigiCertIntegration) error {
	s.mu.Lock()
	s.VerifyProfileIDFuncInvoked = true
	s.mu.Unlock()
	return s.VerifyProfileIDFunc(ctx, config)
}

func (s *Service) GetCertificate(ctx context.Context, config fleet.DigiCertIntegration) (*fleet.DigiCertCertificate, error) {
	s.mu.Lock()
	s.GetCertificateFuncInvoked = true
	s.mu.Unlock()
	return s.GetCertificateFunc(ctx, config)
}
