// Code generated by "stringer -type=automation"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[automation_none-0]
	_ = x[automation_webhook-1]
	_ = x[automation_jira-2]
	_ = x[automation_zendesk-3]
}

const _automation_name = "automation_noneautomation_webhookautomation_jiraautomation_zendesk"

var _automation_index = [...]uint8{0, 15, 33, 48, 66}

func (i automation) String() string {
	if i < 0 || i >= automation(len(_automation_index)-1) {
		return "automation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _automation_name[_automation_index[i]:_automation_index[i+1]]
}
