/**
 * Module dependencies
 */

let ExpressOIDC = require('@okta/oidc-middleware').ExpressOIDC;



/**
 * SSO hook
 */

module.exports = function (sails){

  return {

    defaults: {
      sso: {
        // Default to look for a model w/ identity 'user'
        userModelIdentity: 'user'
      }
    },

    initialize: function (cb) {
      if(!sails.config.custom.ssoClientSecret){
        return cb();
      }
      sails.log('SSO enabled. The built-in authorization mechanism will be disabled.');
      // Throw errors if required config variables are missing.
      if(!sails.config.custom.ssoIssuer){
        throw new Error(`Missing config! No sails.config.custom.ssoIssuer was configured. To replace this app's built-in authorization mechanism with SSO, a ssoIssuer value is required.`);
      }
      if(!sails.config.custom.ssoClientSecret){
        throw new Error(`Missing config! No sails.config.custom.ssoClientSecret was configured. To replace this app's built-in authorization mechanism with SSO, a ssoClientSecret value is required.`);
      }

      // Clone the existing routes
      // NOTE: Changing sails.config after the app lifts goes against Sails.js conventions and this code should not be reproduced.
      let appRoutes = Object.assign({}, sails.config.routes);
      // Remove the routes for the built-in login page..
      delete appRoutes['GET /login'];
      sails.config.routes = Object.assign({}, appRoutes);
      sails.config.http.middleware.order = [
        'cookieParser',
        'session',
        'bodyParser',
        'compress',
        'poweredBy',
        'www',// Note: This changes the conventions of Sails.js. Don't ever replicate this or use Passport.js.
        'sso',
        'router',
        'favicon',
      ];
      // Specify a custom http middleware order, placing the SSO middleware before the router. This is so the routes generated by the OIDC middleware will take precedence over the sails router.
      // Create a passport instance to use
      sails.config.http.middleware.sso = (function() {
        let oidc = new ExpressOIDC({
          issuer: sails.config.custom.ssoIssuer,
          client_id: sails.config.custom.ssoClientId,//eslint-disable-line camelcase
          client_secret: sails.config.custom.ssoClientSecret,//eslint-disable-line camelcase
          appBaseUrl: sails.config.custom.baseUrl,
          scope: 'openid profile email',
          routes: {
            login: {
              path: '/login',
            },
            loginCallback: {
              path: '/authorization-code/callback',
              afterCallback: '/entrance/signup-sso-user-or-redirect',
            },
            logout: {
              path: '/sso/logout'
            },
            logoutCallback: {
              path: '/logout'
            }
          },
        });
        // Sails disables sessions for paths that look like static assets
        // (see sails.config.session.isSessionDisabled). The OIDC router runs
        // passport.session() on every request, which throws "Login sessions
        // require session support" when req.session is undefined — surfacing
        // as a 500 on every static-asset GET for non-logged-in users.
        // Skip the SSO middleware in that case and let the request flow
        // through to the Sails router normally.
        return function ssoMiddleware(req, res, next) {
          if (!req.session) { return next(); }
          return oidc.router(req, res, next);
        };
      })();

      var err;
      // Validate `userModelIdentity` config
      if (typeof sails.config.sso.userModelIdentity !== 'string') {
        sails.config.sso.userModelIdentity = 'user';
      }
      sails.config.sso.userModelIdentity = sails.config.sso.userModelIdentity.toLowerCase();



      // We must wait for the `orm` hook before acquiring our user model from `sails.models`
      // because it might not be ready yet.
      if (!sails.hooks.orm) {
        err = new Error();
        err.code = 'E_HOOK_INITIALIZE';
        err.name = 'SSO Hook Error';
        err.message = 'The "SSO" hook depends on the "orm" hook- cannot load the "SSO" hook without it!';
        return cb(err);
      }
      sails.after('hook:orm:loaded', ()=>{

        // Look up configured user model
        var UserModel = sails.models[sails.config.sso.userModelIdentity];

        if (!UserModel) {
          err = new Error();
          err.code = 'E_HOOK_INITIALIZE';
          err.name = 'SSO Hook Error';
          err.message = 'Could not load the SSO hook because `sails.config.sso.userModelIdentity` refers to an unknown model: "'+sails.config.sso.userModelIdentity+'".';
          if (sails.config.sso.userModelIdentity === 'user') {
            err.message += '\nThis option defaults to `user` if unspecified or invalid- maybe you need to set or correct it?';
          }
          return cb(err);
        }

        // It's very important to trigger this callback method when you are finished
        // with the bootstrap!  (otherwise your server will never lift, since it's waiting on the bootstrap)
        cb();

      });

    },

    routes:{
      before: {
        '/*':{
          skipAssets: true,
          fn: function configureSSO(req, res, next) {
            if(sails.config.custom.ssoClientSecret){
              req = _extendReq(req);
            }
            next();
          }
        }
      }
    }
  };
};






/**
 * Normally these methods are added to the global HTTP IncomingMessage
 * prototype, which breaks encapsulation of Passport core.
 * This function is a patch to override this and also attach them to the local req/res.
 * This allows these methods to work for incoming socket requests.
 * @param  {[type]} req [description]
 * @return {[type]}     [description]
 */
function _extendReq(req) {

  /**
   * Terminate an existing login session.
   *
   * @api public
   */
  req.logout =
  req.logOut = function() {
    if (req.session.passport) {
      delete req.session.passport;
    }
  };

  /**
   * Test if request is authenticated.
   *
   * @return {Boolean}
   * @api public
   */
  req.isAuthenticated = function() {
    if(req.session.passport) {
      if (req.session.passport.user) {
        if(req.session.passport.user.tokens) {
          let tokenExpiresAt = (req.session.passport.user.tokens.expires_at * 1000);
          if(tokenExpiresAt > Date.now()){
            return true;
          }
        }
      }
    }
    return false;
  };

  /**
   * Test if request is unauthenticated.
   *
   * @return {Boolean}
   * @api public
   */
  req.isUnauthenticated = function() {
    return !req.isAuthenticated();
  };

  return req;
}
