// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DBService exposes the dev-MySQL backup directory. Mirrors db.rs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../internal/db/models.js";

export function DBBackupsDir(repo: string): $CancellablePromise<string> {
    return $Call.ByID(2077077237, repo);
}

export function DBCheckBackupName(repo: string, rawName: string): $CancellablePromise<db$0.BackupNameCheck> {
    return $Call.ByID(3939561556, repo, rawName).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DBDeleteBackup(repo: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(3786461670, repo, path);
}

export function DBEnsureBackupsDir(repo: string): $CancellablePromise<string> {
    return $Call.ByID(4043155335, repo);
}

export function DBListBackups(repo: string): $CancellablePromise<db$0.BackupEntry[]> {
    return $Call.ByID(1370485830, repo).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DBSaveBackupMeta(path: string, branch: string | null, note: string | null): $CancellablePromise<void> {
    return $Call.ByID(4182758533, path, branch, note);
}

// Private type creation functions
const $$createType0 = db$0.BackupNameCheck.createFrom;
const $$createType1 = db$0.BackupEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
