const defaultConfigOptions = [
  {
    id: 1,
    name: 'disable_distributed',
    type: 'bool',
    value: false,
    read_only: true,
  },
  {
    id: 2,
    name: 'distributed_plugin',
    type: 'string',
    value: 'tls',
    read_only: true,
  },
  {
    id: 3,
    name: 'distributed_tls_read_endpoint',
    type: 'string',
    value: '/api/v1/osquery/distributed/read',
    read_only: true,
  },
  {
    id: 4,
    name: 'distributed_tls_write_endpoint',
    type: 'string',
    value: '/api/v1/osquery/distributed/write',
    read_only: true,
  },
  {
    id: 5,
    name: 'pack_delimiter',
    type: 'string',
    value: '/',
    read_only: true,
  },
  {
    id: 6,
    name: 'aws_access_key_id',
    type: 'string',
    value: null,
    read_only: false,
  },
  {
    id: 7,
    name: 'aws_firehose_period',
    type: 'int',
    value: null,
    read_only: false,
  },
  {
    id: 8,
    name: 'aws_firehose_stream',
    type: 'string',
    value: null,
    read_only: false,
  },
  {
    id: 9,
    name: 'aws_kinesis_period',
    type: 'int',
    value: null,
    read_only: false,
  },
  {
    id: 10,
    name: 'aws_kinesis_random_partition_key',
    type: 'bool',
    value: null,
    read_only: false,
  },
  {
    id: 11,
    name: 'aws_kinesis_stream',
    type: 'string',
    value: null,
    read_only: false,
  },
  {
    id: 12,
    name: 'aws_profile_name',
    type: 'string',
    value: null,
    read_only: false,
  },
  {
    id: 13,
    name: 'aws_region',
    type: 'string',
    value: null,
    read_only: false,
  },
  {
    id: 14,
    name: 'aws_secret_access_key',
    type: 'string',
    value: null,
    read_only: false,
  },
  {
    id: 15,
    name: 'aws_sts_arn_role',
    type: 'string',
    value: null,
    read_only: false,
  },
  {
    id: 16,
    name: 'aws_sts_region',
    type: 'string',
    value: null,
    read_only: false,
  },
  {
    id: 17,
    name: 'aws_sts_session_name',
    type: 'string',
    value: null,
    read_only: false,
  },
  {
    id: 18,
    name: 'aws_sts_timeout',
    type: 'int',
    value: null,
    read_only: false,
  },
  {
    id: 19,
    name: 'buffered_log_max',
    type: 'int',
    value: null,
    read_only: false,
  },
  {
    id: 20,
    name: 'decorations_top_level',
    type: 'bool',
    value: null,
    read_only: false,
  },
  {
    id: 21,
    name: 'disable_caching',
    type: 'bool',
    value: null,
    read_only: false,
  },
  {
    id: 22,
    name: 'disable_database',
    type: 'bool',
    value: null,
    read_only: false,
  },
  {
    id: 23,
    name: 'disable_decorators',
    type: 'bool',
    value: null,
    read_only: false,
  },
  {
    id: 24,
    name: 'disable_events',
    type: 'bool',
    value: null,
    read_only: false,
  },
  {
    id: 25,
    name: 'disable_kernel',
    type: 'bool',
    value: null,
    read_only: false,
  },
  {
    id: 26,
    name: 'disable_logging',
    type: 'bool',
    value: null,
    read_only: false,
  },
  {
    id: 27,
    name: 'disable_tables',
    type: 'string',
    value: null,
    read_only: false,
  },
  {
    id: 28,
    name: 'distributed_interval',
    type: 'int',
    value: 10,
    read_only: false,
  },
  {
    id: 29,
    name: 'distributed_tls_max_attempts',
    type: 'int',
    value: 3,
    read_only: false,
  },
  {
    id: 30,
    name: 'enable_foreign',
    type: 'bool',
    value: null,
    read_only: false,
  },
  {
    id: 31,
    name: 'enable_monitor',
    type: 'bool',
    value: null,
    read_only: false,
  },
  {
    id: 32,
    name: 'ephemeral',
    type: 'bool',
    value: null,
    read_only: false,
  },
  {
    id: 33,
    name: 'events_expiry',
    type: 'int',
    value: null,
    read_only: false,
  },
  {
    id: 34,
    name: 'events_max',
    type: 'int',
    value: null,
    read_only: false,
  },
  {
    id: 35,
    name: 'events_optimize',
    type: 'bool',
    value: null,
    read_only: false,
  },
  {
    id: 36,
    name: 'host_identifier',
    type: 'string',
    value: null,
    read_only: false,
  },
  {
    id: 37,
    name: 'logger_event_type',
    type: 'bool',
    value: null,
    read_only: false,
  },
  {
    id: 38,
    name: 'logger_mode',
    type: 'string',
    value: null,
    read_only: false,
  },
  {
    id: 39,
    name: 'logger_path',
    type: 'string',
    value: null,
    read_only: false,
  },
  {
    id: 40,
    name: 'logger_plugin',
    type: 'string',
    value: 'tls',
    read_only: false,
  },
  {
    id: 41,
    name: 'logger_secondary_status_only',
    type: 'bool',
    value: null,
    read_only: false,
  },
  {
    id: 42,
    name: 'logger_syslog_facility',
    type: 'int',
    value: null,
    read_only: false,
  },
  {
    id: 43,
    name: 'logger_tls_compress',
    type: 'bool',
    value: null,
    read_only: false,
  },
  {
    id: 44,
    name: 'logger_tls_endpoint',
    type: 'string',
    value: '/api/v1/osquery/log',
    read_only: false,
  },
  {
    id: 45,
    name: 'logger_tls_max',
    type: 'int',
    value: null,
    read_only: false,
  },
  {
    id: 46,
    name: 'logger_tls_period',
    type: 'int',
    value: 10,
    read_only: false,
  },
  {
    id: 47,
    name: 'pack_refresh_interval',
    type: 'int',
    value: null,
    read_only: false,
  },
  {
    id: 48,
    name: 'read_max',
    type: 'int',
    value: null,
    read_only: false,
  },
  {
    id: 49,
    name: 'read_user_max',
    type: 'int',
    value: null,
    read_only: false,
  },
  {
    id: 50,
    name: 'schedule_default_interval',
    type: 'int',
    value: null,
    read_only: false,
  },
  {
    id: 51,
    name: 'schedule_splay_percent',
    type: 'int',
    value: null,
    read_only: false,
  },
  {
    id: 52,
    name: 'schedule_timeout',
    type: 'int',
    value: null,
    read_only: false,
  },
  {
    id: 53,
    name: 'utc',
    type: 'bool',
    value: null,
    read_only: false,
  },
  {
    id: 54,
    name: 'value_max',
    type: 'int',
    value: null,
    read_only: false,
  },
  {
    id: 55,
    name: 'verbose',
    type: 'bool',
    value: null,
    read_only: false,
  },
  {
    id: 56,
    name: 'worker_threads',
    type: 'int',
    value: null,
    read_only: false,
  },
];

export default defaultConfigOptions;
