#!/bin/bash
source $FLEET_ENV_PATH
endpoint="api/v1/fleet/packs"
jq -n \
  --arg name "$1" \
  '.name = $name 
  |.disabled = false
  '|\
  curl $CURL_FLAGS -H "Authorization: Bearer $TOKEN" "$SERVER_URL/$endpoint" -d@- 
