name: JavaScript Tests

on:
  push:
    branches:
      - main
      - patch-*
      - prepare-*
  pull_request:
    paths:
      - assets/**
      - frontend/**
      - package.json
      - yarn.lock
      - webpack.config.js
      - tsconfig.json

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  test-js:
    strategy:
      matrix:
        os: [ubuntu-4core]
    runs-on: ${{ matrix.os }}

    steps:
      # Set the Node.js version
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: package.json

      - name: JS Dependency Cache
        id: js-cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install JS Dependencies
        if: steps.js-cache.outputs.cache-hit != 'true'
        run: make deps-js

      - name: Run JS Tests
        run: |
          yarn test:ci

      - name: Upload to Codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend

  lint-js:
    strategy:
      matrix:
        os: [ubuntu-4core]
    runs-on: ${{ matrix.os }}

    steps:
      # Set the Node.js version
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: package.json

      - name: JS Dependency Cache
        id: js-cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install JS Dependencies
        if: steps.js-cache.outputs.cache-hit != 'true'
        run: make deps-js

      - name: Run JS Linting
        run: |
          make lint-js

      - name: Run prettier formatting check
        run: |
          yarn prettier:check
