name: tfvalidate

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
  pull_request:
    paths:
      - '**.tf'
  workflow_dispatch: # Manual dispatch

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

defaults:
  run:
    # fail-fast using bash -eo pipefail. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    shell: bash

permissions:
  contents: read

jobs:
  tfvalidate:
    name: terraform validate
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9ca718d3bf646d6534007c269a635b3e54cadf99 # v2.19.2
        with:
          egress-policy: audit

      - name: Clone repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: 1.12.0
      # If we want to test more of these, consider using a matrix.  With a matrix of directories, all terraform modules could be fully tested and potentially in parallel.
      - name: Validate loadtesting
        working-directory: ./infrastructure/loadtesting/terraform
        run: |
          terraform init -backend=false
          terraform validate

      - name: Validate infrastructure
        working-directory: ./infrastructure/infrastructure/terraform
        run: |
          terraform init -backend=false
          terraform validate

      - name: Validate dogfood
        working-directory: ./infrastructure/dogfood/terraform/aws-tf-module
        run: |
          terraform init -backend=false
          terraform validate

      - name: Validate root terraform module
        working-directory: ./terraform
        run: |
          terraform init -backend=false
          terraform validate
