---
x-default-settings:
  environment: &default-environment
    ENROLL_SECRET: "${ENROLL_SECRET:?ENROLL_SECRET must be set for server authentication}"
  ulimits: &default-ulimits
    core:
      hard: 1000000000
      soft: 1000000000
  network_mode: &default-network-mode bridge
  extra_hosts: &extra-hosts
    - "host.docker.internal:host-gateway"
  platform: &default-platform linux/amd64

#
# We are running the containers with `privileged: true` to fix osquery errors like
# `[... processes.cpp:510] Cannot read /proc/50/io (is osquery running as root?)`
# (it is running as `root` but seems it's missing some privileges in the container).
#

services:
  ubuntu24.04-fleetd:
    image: "fleetd-ubuntu-24.04"
    privileged: true
    user: 0:0
    network_mode: *default-network-mode
    platform: *default-platform
    environment: *default-environment
    ulimits: *default-ulimits
    extra_hosts: *extra-hosts
  fedora43-fleetd:
    image: "fleetd-fedora-43"
    privileged: true
    user: 0:0
    network_mode: *default-network-mode
    platform: *default-platform
    environment: *default-environment
    ulimits: *default-ulimits
    extra_hosts: *extra-hosts
  debian13.4-fleetd:
    image: "fleetd-debian-13.4"
    privileged: true
    user: 0:0
    network_mode: *default-network-mode
    platform: *default-platform
    environment: *default-environment
    ulimits: *default-ulimits
    extra_hosts: *extra-hosts
  amazonlinux2023-fleetd:
    image: "fleetd-amazonlinux-2023"
    privileged: true
    user: 0:0
    network_mode: *default-network-mode
    platform: *default-platform
    environment: *default-environment
    ulimits: *default-ulimits
    extra_hosts: *extra-hosts
