fleet-gitops:
  image: debian:bookworm-slim
  variables:
    FLEET_DRY_RUN_ONLY: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        FLEET_DRY_RUN_ONLY: false
    - if: $CI_PIPELINE_SOURCE == 'schedule' && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        FLEET_DRY_RUN_ONLY: false
  before_script:
    - apt-get -qq update
    - apt-get install -y curl 'jq=1.6-2.1*'
  script:
    - >
      FLEET_VERSION="$(curl "$FLEET_URL/api/v1/fleet/version" --header "Authorization: Bearer $FLEET_API_TOKEN" --fail --silent | jq --raw-output '.version')"
    - >
      if [[ -n "$FLEET_VERSION" ]] ; then
        curl -fsSL https://fleetdm.com/resources/install-fleetctl.sh | FLEETCTL_VERSION="$FLEET_VERSION" bash || curl -fsSL https://fleetdm.com/resources/install-fleetctl.sh | bash
      else
        echo "Failed to get Fleet version from $FLEET_URL, installing latest version of fleetctl"
        curl -fsSL https://fleetdm.com/resources/install-fleetctl.sh | bash
      fi
    - export PATH="$HOME/.fleetctl:$PATH"
    - fleetctl config set --address $FLEET_URL --token $FLEET_API_TOKEN
    - ./.github/fleet-gitops/gitops.sh
